
import { Language } from './types';

export const AVATARS = [
  "https://robohash.org/Felix.png?set=set5&bgset=bg1",
  "https://robohash.org/Aneka.png?set=set5&bgset=bg1",
  "https://robohash.org/Pepper.png?set=set5&bgset=bg1",
  "https://robohash.org/George.png?set=set5&bgset=bg1",
  "https://robohash.org/Molly.png?set=set5&bgset=bg1",
  "https://robohash.org/Tech.png?set=set5&bgset=bg1",
  "https://robohash.org/Sasha.png?set=set5&bgset=bg1",
  "https://robohash.org/Alex.png?set=set5&bgset=bg1",
  "https://robohash.org/Jace.png?set=set5&bgset=bg1",
  "https://robohash.org/Oliver.png?set=set5&bgset=bg1",
  "https://robohash.org/Willow.png?set=set5&bgset=bg1",
  "https://robohash.org/Zoe.png?set=set5&bgset=bg1",
  "https://robohash.org/Leo.png?set=set5&bgset=bg1",
  "https://robohash.org/Chloe.png?set=set5&bgset=bg1",
  "https://robohash.org/Max.png?set=set5&bgset=bg1",
  "https://robohash.org/Sam.png?set=set5&bgset=bg1",
  "https://robohash.org/Robot01.png?set=set5&bgset=bg1",
  "https://robohash.org/Happy.png?set=set5&bgset=bg1",
  "https://robohash.org/Buddy.png?set=set5&bgset=bg1",
  "https://robohash.org/Maria.png?set=set5&bgset=bg1",
  "https://robohash.org/Jack.png?set=set5&bgset=bg1",
  "https://robohash.org/Sarah.png?set=set5&bgset=bg1",
  "https://robohash.org/David.png?set=set5&bgset=bg1",
  "https://robohash.org/Emma.png?set=set5&bgset=bg1",
  "https://robohash.org/Bot2.png?set=set5&bgset=bg1",
  "https://robohash.org/Lily.png?set=set5&bgset=bg1",
  "https://robohash.org/Tom.png?set=set5&bgset=bg1",
  "https://robohash.org/Mia.png?set=set5&bgset=bg1",
  "https://robohash.org/Noah.png?set=set5&bgset=bg1",
  "https://robohash.org/Olivia.png?set=set5&bgset=bg1"
];

// Updated to Object for localization
export const CAREER_TAGS = [
  { en: "Software Engineer", vi: "Kỹ sư phần mềm" },
  { en: "Data Scientist", vi: "Khoa học dữ liệu" },
  { en: "Product Manager", vi: "Quản lý sản phẩm" },
  { en: "UX Designer", vi: "Thiết kế UX/UI" },
  { en: "Digital Marketing", vi: "Tiếp thị số" },
  { en: "Cybersecurity", vi: "An ninh mạng" },
  { en: "Blockchain Dev", vi: "Lập trình Blockchain" },
  { en: "AI Specialist", vi: "Chuyên gia AI" },
  { en: "Cloud Architect", vi: "Kiến trúc sư đám mây" },
  { en: "Content Creator", vi: "Sáng tạo nội dung" },
  { en: "Growth Hacker", vi: "Tăng trưởng số" },
  { en: "DevOps Engineer", vi: "Kỹ sư DevOps" }
];

export const HOT_INDUSTRIES = [
  { 
    id: 1, 
    name_en: "Artificial Intelligence", 
    name_vi: "Trí tuệ nhân tạo (AI)", 
    desc_en: "The driving force of the future. Roles in ML, NLP, and Data are booming.", 
    desc_vi: "Động lực của tương lai. Các vai trò về ML, NLP và Dữ liệu đang bùng nổ.", 
    color: "from-blue-500 to-indigo-600",
    icon: "Cpu"
  },
  { 
    id: 2, 
    name_en: "Green Energy & Sustainability", 
    name_vi: "Năng lượng xanh & Bền vững", 
    desc_en: "Fighting climate change with tech. High demand for engineers and analysts.", 
    desc_vi: "Chống biến đổi khí hậu bằng công nghệ. Nhu cầu cao về kỹ sư và nhà phân tích.", 
    color: "from-emerald-400 to-teal-600",
    icon: "Leaf"
  },
  { 
    id: 3, 
    name_en: "Cybersecurity", 
    name_vi: "An ninh mạng", 
    desc_en: "Protecting the digital world. Critical shortage of skilled defenders.", 
    desc_vi: "Bảo vệ thế giới số. Sự thiếu hụt trầm trọng các chuyên gia bảo mật.", 
    color: "from-red-500 to-rose-600",
    icon: "Shield"
  },
  { 
    id: 4, 
    name_en: "Digital Health (HealthTech)", 
    name_vi: "Y tế kỹ thuật số", 
    desc_en: "Telemedicine and BioTech are revolutionizing patient care.", 
    desc_vi: "Khám chữa bệnh từ xa và Công nghệ sinh học đang cách mạng hóa việc chăm sóc bệnh nhân.", 
    color: "from-cyan-400 to-blue-600",
    icon: "Activity"
  },
  { 
    id: 5, 
    name_en: "Fintech & Blockchain", 
    name_vi: "Công nghệ tài chính", 
    desc_en: "Reshaping banking, payments, and decentralized finance.", 
    desc_vi: "Định hình lại ngân hàng, thanh toán và tài chính phi tập trung.", 
    color: "from-violet-500 to-purple-600",
    icon: "CreditCard"
  },
  { 
    id: 6, 
    name_en: "EdTech & E-Learning", 
    name_vi: "Công nghệ giáo dục", 
    desc_en: "Remote learning is here to stay. Opportunities in instructional design and dev.", 
    desc_vi: "Học tập từ xa đang phát triển mạnh. Cơ hội trong thiết kế bài giảng và lập trình.", 
    color: "from-amber-400 to-orange-600",
    icon: "BookOpen"
  },
  { 
    id: 7, 
    name_en: "Semiconductor Industry", 
    name_vi: "Công nghiệp Bán dẫn", 
    desc_en: "The brain of every electronic device. Vietnam is becoming a global hub.", 
    desc_vi: "Bộ não của mọi thiết bị điện tử. Việt Nam đang trở thành trung tâm toàn cầu.", 
    color: "from-indigo-500 to-blue-700",
    icon: "Cpu"
  },
  { 
    id: 8, 
    name_en: "E-Commerce & Logistics", 
    name_vi: "Thương mại điện tử & Logistics", 
    desc_en: "Powering the global supply chain and the future of online retail.", 
    desc_vi: "Vận hành chuỗi cung ứng toàn cầu và tương lai của bán lẻ trực tuyến.", 
    color: "from-orange-500 to-red-600",
    icon: "Globe"
  },
  { 
    id: 9, 
    name_en: "Robotics & Automation", 
    name_vi: "Robot & Tự động hóa", 
    desc_en: "Creating smart machines to assist and automate complex tasks.", 
    desc_vi: "Chế tạo máy móc thông minh để hỗ trợ và tự động hóa các tác vụ phức tạp.", 
    color: "from-gray-500 to-slate-700",
    icon: "Server"
  },
  { 
    id: 10, 
    name_en: "Creative & Digital Media", 
    name_vi: "Sáng tạo & Truyền thông số", 
    desc_en: "Content creation, UI/UX design, and digital entertainment.", 
    desc_vi: "Sáng tạo nội dung, thiết kế UI/UX và giải trí kỹ thuật số.", 
    color: "from-fuchsia-500 to-pink-600",
    icon: "Camera"
  }
];

export const CAREER_QUOTES = [
  { text: "Choose a job you love, and you will never have to work a day in your life.", text_vi: "Hãy chọn công việc bạn yêu thích, và bạn sẽ không bao giờ phải làm việc một ngày nào trong đời.", author: "Confucius" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", text_vi: "Tương lai thuộc về những ai tin vào vẻ đẹp của giấc mơ của mình.", author: "Eleanor Roosevelt" },
  { text: "Opportunities don't happen, you create them.", text_vi: "Cơ hội không tự đến, bạn phải tạo ra chúng.", author: "Chris Grosser" },
  { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", text_vi: "Công việc sẽ chiếm phần lớn cuộc đời bạn, cách duy nhất để thực sự hài lòng là làm những gì bạn tin là tuyệt vời.", author: "Steve Jobs" }
];

export const SUGGESTION_PROMPTS = {
  [Language.EN]: [
    { title: 'Identify Strengths', prompt: 'Can you help me identify my core strengths and how they apply to a career?', icon: 'Activity' },
    { title: 'Discover Passion', prompt: 'I am not sure what I am passionate about. How can I discover my true interests?', icon: 'Heart' },
    { title: 'Career Roadmap', prompt: 'I want to become a Software Engineer. Can you create a 3-month roadmap for me?', icon: 'Target' },
    { title: 'Explore Industries', prompt: 'What are the top trending industries in Vietnam right now for high school graduates?', icon: 'Compass' }
  ],
  [Language.VI]: [
    { title: 'Tìm điểm mạnh', prompt: 'Bạn có thể giúp tôi xác định các điểm mạnh cốt lõi và cách áp dụng chúng vào sự nghiệp không?', icon: 'Activity' },
    { title: 'Khám phá đam mê', prompt: 'Tôi không chắc mình đam mê điều gì. Làm thế nào để tôi khám phá được sở thích thực sự của mình?', icon: 'Heart' },
    { title: 'Lộ trình sự nghiệp', prompt: 'Tôi muốn trở thành Kỹ sư phần mềm. Bạn có thể lập lộ trình 3 tháng cho tôi không?', icon: 'Target' },
    { title: 'Khám phá ngành nghề', prompt: 'Những ngành nghề nào đang là xu hướng hàng đầu tại Việt Nam hiện nay cho học sinh tốt nghiệp THPT?', icon: 'Compass' }
  ]
};

export const TRANSLATIONS = {
  [Language.EN]: {
    appName: 'CareerGuide AI', home: 'Home', tagline: 'Career guidance for everyone.', subTagline: 'Pause or cancel your confusion anytime. Available 24/7.', getStarted: 'Get Started', login: 'Login', register: 'Register', guestLogin: 'Try as Guest', email: 'Email Address', password: 'Password', forgotPassword: 'Forgot Password?', loginWithGoogle: 'Login with Google', or: 'or', dontHaveAccount: "Don't have an account?", alreadyHaveAccount: 'Already have an account?', chatMode: 'Chat Consultant', voiceMode: 'Live Consultation', profile: 'My Profile', welcomeBack: 'Welcome Back,', greeting: "How can I help you today?", greetingSub: "Ask me about careers, majors, or RIASEC results.", typeMessage: 'Type your career question...', startVoice: 'Start Live Conversation', endVoice: 'End Conversation', listening: 'Listening...', speaking: 'Speaking...', connecting: 'Connecting to CareerGuide AI...', disconnecting: 'Disconnecting...', micPermission: 'Mic access required', readyToConnect: 'Ready to connect', error: 'An error occurred. Please try again.', hotIndustries: 'Trending Industries', dailyQuote: 'Daily Inspiration', chatHistory: 'Chat History', switchToVoice: 'Switch to Live Voice', newChat: 'New Chat', footerDisclaimer: 'AI can make mistakes. All information is for reference only, the decision is yours.', thinking: 'Thinking...', thinkingPassions: 'Exploring your passions...', thinkingOpportunities: 'Analyzing career opportunities...', thinkingMarket: 'Researching market compensation...', thinkingProfile: 'Reviewing your profile...', thinkingPaths: 'Mapping learning paths...', profileName: 'Full Name', careerGoal: 'Career Goal', prefLang: 'Preferred Language', langName: 'English', langEn: 'English', langVi: 'Vietnamese', saveChanges: 'Save Changes', guestMode: 'Guest Mode', guest: 'Guest', undecided: 'Undecided', exploring: 'Exploring', selectMic: 'Select Microphone', transcript: 'Live Transcript', aiBusy: 'The AI is currently busy due to high demand. Please wait a moment and try again.', failedRoadmapFormat: 'Failed to generate roadmap format.', noAiResponse: 'No response from AI.', failedToCommunicate: 'Failed to communicate with the server.', noExternalResponse: 'No response from external model.', mediaNotSupported: 'MediaDevices API not supported. Please use HTTPS.', connectionFailed: 'Connection failed. Please check your network or try again.', tempChatTooltip: 'Temporary chat messages will not be saved to history.', temporaryChat: 'Temporary Chat', uploadFile: 'Upload File', takePhoto: 'Take Photo', live: 'Live', readyToStart: 'Ready to start', universityScores: 'University Scores', careerCompare: 'Career Compare', trendingCareers: 'Vietnam Hot Jobs', mockInterview: 'Mock Interview', promptBuilder: 'AI Prompt Builder', careerLifecycle: 'Career Lifecycle', monetizationPartners: 'Plans & Partners',
    
    // Auth - Forgot Password
    resetPasswordTitle: 'Reset Password',
    resetPasswordDesc: 'Enter your email address and we will send you instructions to reset your password.',
    sendLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    linkSent: 'Success! Please check your email for the reset link.',

    // AI Config
    aiConfigTitle: 'AI Model Configuration',
    aiProvider: 'AI Provider',
    providerGemini: 'CareerGuide AI',
    providerCustom: 'Custom (OpenAI)',
    providerN8N: 'n8n Workflow',
    endpointUrl: 'Endpoint URL',
    n8nWebhookUrl: 'n8n Webhook URL (POST)',
    endpointNote: 'Compatible with Ollama, vLLM, or LM Studio.',
    n8nNote: 'Requires a Webhook node (POST) returning a JSON property "output" or "text".',
    modelName: 'Model Name',
    
    // New Translations
    chatPlaceholder: 'Ask me anything about your career...',
    heroBadge: 'AI-Powered Guidance',
    heroTitlePrefix: 'Career clarity for ',
    heroTitleSuffix: 'everyone',
    hotIndustriesTitle: 'Future-Proof Your Career',
    hotIndustriesSub: 'Discover high-growth industries where our AI can help you navigate and land your dream role.',
    vnLaborMarketTitle: 'VN Labor Market 2024-2025',
    vnLaborMarketDesc: 'High demand for skilled talent in Tech (AI, Semiconductor), Logistics, and Renewable Energy is skyrocketing.',
    careerQuizTitle: 'Career Quiz',
    careerQuizDesc: 'Discover your career personality group (RIASEC) in just 2 minutes.',
    accuracyRate: 'AI Accuracy Rate',
    userCount: 'Trusted Users',
    activeSessions: '24h Sessions',
    accuracyValue: '98.5%',
    userValue: '12,500+',
    sessionValue: '1,240',
    dashboard: 'Dashboard',
    growthRate: 'Growth Rate',
    empoweringFutures: 'Empowering Futures',
    backToHome: 'Back to Home',
    noResultsFound: 'No results found',
    generateRoadmap: 'Generate Career Roadmap',
    basedOnHistory: 'Based on your conversation history',
    enterNewPassword: 'Enter your new password below.',
    enterResetCode: 'Enter the 8-digit code sent to your email.',
    updatePassword: 'Update Password',
    verifyCode: 'Verify Code',
    sendVerificationCode: 'Send Verification Code',
    codeSent: 'Code sent!',
    verificationCode: 'Verification Code',
    resendCode: 'Resend Code / Change Email',
    fullName: 'Full Name',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    attach: 'Attach',
    close: 'Close',
    fillAllFields: 'Please fill all fields',
    emailRegistered: 'Email already registered',
    invalidLogin: 'Invalid email or password',
    firebaseNotConfigured: 'Firebase not configured. Please check console.',
    loginFailed: 'Login Failed:',
    enterEmail: 'Please enter your email',
    googleLoginRequired: 'This account uses Google Login. Please login with Google instead.',
    emailNotFound: 'Email not found. Please Register an account first.',
    failedToSendEmail: 'Failed to send email. Please check your internet connection or try again later.',
    invalidCode: 'Invalid verification code.',
    passwordsDoNotMatch: 'Passwords do not match',
    userNotFound: 'User not found.',
    passwordUpdated: 'Password updated successfully! Please login.',
    profileSaved: 'Settings Saved!',
    chatCleared: 'Chat history cleared',
    sessionCleared: 'Current session cleared',
    imageTooLarge: 'Image size should be less than 5MB.',
    invalidImage: 'Please select a valid image file.',
    cameraDenied: 'Camera access denied or not available.',
    failedToLoadImage: 'Failed to load image.',
    failedToReadFile: 'Failed to read file.',
    failedToSaveProfile: 'Failed to save profile. The image might be too large.',
    roadmapUpdated: 'Roadmap updated successfully!',
    loginToSetGoal: 'Please login to set your career goal.',
    syncToProgress: 'Sync to Progress',
    pasted: 'PASTED',
    microphone: 'Microphone', startListening: 'Start listening', stopListening: 'Stop listening', voiceInput: 'Voice input',
    failedToGenerateRoadmap: 'Failed to generate roadmap. Please try again.',
    preparingPDF: 'Preparing your PDF...',
    pdfExportSuccess: 'PDF exported successfully!',
    exportFailed: 'Export failed. Please try again.',
    generatingImage: 'Generating image...',
    imageSaveSuccess: 'Image saved successfully!',
    imageSaveFailed: 'Image save failed. Please try again.',
    statusDone: 'Done',
    statusInProgress: 'In Progress',
    statusTodo: 'To Do',
    roadmapEmptyTitle: 'Your Roadmap is Empty',
    roadmapEmptyDesc: 'Chat with the AI first so it can understand your goals and generate a personalized step-by-step career roadmap for you.',
    startChatting: 'Start Chatting',
    generating: 'Generating...',
    generateRoadmapNow: 'Generate Roadmap',
    careerRoadmap: 'Career Roadmap',
    roadmapSub: 'Track your progress and export to share.',
    saveImage: 'Save Image',
    exportPDF: 'Export PDF',
    personalProfile: 'Personal Profile',
    progressBoardTitle: 'Progress Board',
    progressBoardSub: 'Click on items to update status',
    addNotePlaceholder: 'Add a note or evaluation...',
    generatedBy: 'Generated by CareerGuide AI',
    dateLabel: 'Date:',
    generatingDocument: 'Generating Document',
    preparingFile: 'Please wait a moment while we prepare your file...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    enterTitleError: 'Please enter a title',
    itemAdded: 'Item added to portfolio',
    itemRemoved: 'Item removed',
    placeholderPortfolioTitle: 'e.g. IELTS 8.0',
    pdfFilename: 'Career-Roadmap.pdf',
    imageFilename: 'Career-Roadmap.png',
    quizResultTitle: 'Your Career Profile',
    quizAdvicePrompt: 'I just finished the RIASEC quiz and my result is {{result}}. Can you give me some career advice based on this?',
    retakeQuiz: 'Retake Quiz',
    discussWithAI: 'Discuss with AI',
    question: 'Question',
    of: 'of',
    quizNo: 'No',
    quizMaybe: 'Maybe',
    quizYes: 'Yes',
    quizRealistic: 'Realistic: You are practical and hands-on.',
    quizInvestigative: 'Investigative: You are analytical and curious.',
    quizArtistic: 'Artistic: You are creative and expressive.',
    quizSocial: 'Social: You are helpful and empathetic.',
    quizEnterprising: 'Enterprising: You are ambitious and persuasive.',
    quizConventional: 'Conventional: You are organized and detail-oriented.',
    quizQ1: 'I like to work with animals, tools, or machines.',
    quizQ2: 'I like to solve math and science problems.',
    quizQ3: 'I like to do creative activities like art, drama, or music.',
    quizQ4: 'I like to help, teach, or provide service to others.',
    quizQ5: 'I like to lead and persuade people.',
    quizQ6: 'I like to work with numbers, records, or machines in an orderly way.',
    quizQ7: 'I enjoy repairing things.',
    quizQ8: 'I enjoy conducting experiments.',
    quizQ9: 'I enjoy writing stories or poems.',
    quizQ10: 'I enjoy volunteering for social causes.',
    quizQ11: 'I enjoy starting my own business.',
    quizQ12: 'I enjoy organizing data and files.',
    continueJourney: 'Ready to continue your journey,',
    goToDashboard: 'Go to Dashboard',
    guestSession: 'Guest Session',
    logout: 'Logout',
    chooseAvatar: 'Choose Default Avatar',
    randomAvatar: 'Random Avatar',
    searchChats: 'Search chats...',
    collapseSidebar: 'Collapse sidebar',
    expandSidebar: 'Expand sidebar',
    progress: 'Progress',
    scholarships: 'Scholarships',
    findScholarships: 'Find Scholarships',
    scholarshipDesc: 'Discover AI-matched scholarships and financial aid programs based on your goals and profile.',
    scholarshipSearchPlaceholder: 'E.g., Engineering scholarships in the US for undergraduate students...',
    storageManagement: 'Storage Management',
    manageChatData: 'Manage your persistent chat data',
    clearAllHistory: 'Clear All History',
    clearHistoryConfirm: 'Are you sure you want to clear all chat history? This cannot be undone.',
    streakTooltip: '{{streak}} day streak!',
    
    // Portfolio
    portfolio: 'Portfolio / CV',
    portfolioDesc: 'Store your certificates, grades, and personal projects. Export as a complete CV/Portfolio for college applications.',
    addPortfolioItem: 'Add Item',
    itemType: 'Type',
    typeCertificate: 'Certificate',
    typeGrade: 'Grade/Score',
    typeProject: 'Personal Project',
    itemTitle: 'Title',
    itemDesc: 'Description',
    itemDate: 'Date/Period',
    itemScore: 'Score/Result',
    itemLink: 'Link (Optional)',
    exportCV: 'Export CV/Portfolio',
    noPortfolioItems: 'No items in your portfolio yet. Add your achievements to build your CV!',
    
    // Feature Translations - UPDATED
    featureVoiceTitle: 'Direct 1-on-1 Consultation',
    featureVoiceDesc: 'Voice chat with AI just like a real academic advisor. Get instant feedback and personalized guidance.',
    feature247Title: 'Always Available',
    feature247Desc: 'No appointments. No waiting. Career advice whenever you need it.',
    featureScanTitle: 'Academic Profile Analysis',
    featureScanDesc: 'AI-powered analysis of your grades and activities to suggest the best academic tracks.',
    featureRoadmapTitle: 'Personalized Roadmap',
    featureRoadmapDesc: 'From identifying your strengths to choosing the right major, we map out every step specifically for you.',
    featureHeader: 'The way career guidance',
    featureHeaderHighlight: 'should',
    featureHeaderSuffix: 'have always been.',
    featureSub: 'One platform replacing expensive counselors and scattered Google searches.',
    
    systemInstruction: 'You are an expert career counselor for high school students named Career Guide AI. Your mission is to help students identify their strengths, choose the right academic tracks (khối thi), majors, and universities in Vietnam. Your goal is to be as helpful as possible while ensuring accuracy. Answer questions directly, naturally, and warmly in a conversational tone. Do NOT output clarification question JSON blocks. ONLY when the user explicitly requests a roadmap, a plan, or asks to update their progress board, you should provide a structured 3-month development roadmap by outputting a JSON block like this: ```json [{"id": "1", "title": "Month 1: Step 1", "description": "Details for month 1", "status": "todo"}] ```. Do NOT include this JSON block in normal conversation unless specifically requested. The roadmap MUST be limited to a 3-month timeframe, avoiding overly long-term plans. Encourage the user to sync this to their board to track their progress. Be professional, encouraging, and concise. If the user shares a RIASEC profile, use it for personalized suggestions. Use English and Vietnamese only.',
    voiceSystemInstruction: 'You are the Career Compass AI Counselor. MANDATORY RULES: 1. Respond 100% in English naturally and warmly. 2. NEVER output internal thoughts, reasoning steps, or English meta headers (e.g. do not output "Confirming...", "Analyzing..."). 3. Answer immediately in 1-2 concise, conversational sentences (maximum 35 words). 4. Never use asterisks (*) or markdown formatting.',
    
    // Terms of Service
    termsTitle: 'Terms of Service & Disclaimer',
    terms1: '1. Acceptance of Terms:',
    terms1Desc: 'By using CareerGuide AI, you agree to these terms.',
    terms2: '2. AI Limitations:',
    terms2Desc: 'The career advice provided is generated by Artificial Intelligence. It may contain errors, inaccuracies, or outdated information.',
    terms3: '3. No Professional Liability:',
    terms3Desc: 'This tool is for educational and informational purposes only. It does not replace professional career counseling, legal, or financial advice.',
    terms4: '4. Data Privacy:',
    terms4Desc: 'We respect your privacy. Uploaded images and chat logs are processed securely but please avoid sharing highly sensitive personal information.',
    terms5: '5. User Responsibility:',
    terms5Desc: 'You are solely responsible for any decisions made based on the AI\'s suggestions.',
    termsAccept: 'I Understand & Got It',
    placeholderName: 'John Doe',
    placeholderEmail: 'name@example.com',
    placeholderPassword: '••••••••',
    placeholderSearch: 'Search...',
    placeholderCareerGoal: 'Your career goal...',
    placeholderPortfolioDesc: 'Brief description of your achievement...',
    placeholderPortfolioScore: 'Score, GPA, or result...',
    placeholderPortfolioDate: '2023 - 2024',
    placeholderMessage: 'Type a message...',
    placeholderResetCode: 'Enter 8-digit code...',
    placeholderNewPassword: 'New password',
    placeholderConfirmPassword: 'Confirm new password',
    placeholderAdvice: 'Any advice for me?',
    placeholderBio: 'Tell us a bit about yourself...',
    welcomePhrases: [
      "Share your ideas with me!",
      "What's on your mind today?",
      "Let's explore your future together!",
      "Ready to find your dream career?"
    ],
    laborMarketTags: [
      { en: 'AI Engineer', vi: 'Kỹ sư AI' },
      { en: 'Logistics Manager', vi: 'Quản lý Logistics' },
      { en: 'Semiconductor Tech', vi: 'Kỹ thuật Bán dẫn' },
      { en: 'Green Energy', vi: 'Năng lượng xanh' }
    ]
  },
  [Language.VI]: {
    appName: 'CareerGuide AI', home: 'Trang chủ', tagline: 'Hướng nghiệp cho mọi người.', subTagline: 'Xóa tan mọi sự bối rối về sự nghiệp. Sẵn sàng 24/7.', getStarted: 'Bắt đầu ngay', login: 'Đăng nhập', register: 'Đăng ký', guestLogin: 'Dùng thử ngay', email: 'Địa chỉ Email', password: 'Mật khẩu', forgotPassword: 'Quên mật khẩu?', loginWithGoogle: 'Đăng nhập bằng Google', or: 'hoặc', dontHaveAccount: "Chưa có tài khoản?", alreadyHaveAccount: 'Đã có tài khoản?', chatMode: 'Trợ lý Chat', voiceMode: 'Hội thoại trực tiếp', profile: 'Hồ sơ cá nhân', welcomeBack: 'Chào mừng trở lại,', greeting: "Tôi có thể giúp gì cho bạn?", greetingSub: "Hỏi tôi về nghề nghiệp, ngành học hoặc kết quả RIASEC.", typeMessage: 'Nhập câu hỏi của bạn...', startVoice: 'Bắt đầu cuộc gọi', endVoice: 'Kết thúc cuộc gọi', listening: 'Đang nghe...', speaking: 'Đang nói...', connecting: 'Đang kết nối...', disconnecting: 'Đang ngắt kết nối...', micPermission: 'Cần cấp quyền micro', readyToConnect: 'Sẵn sàng kết nối', error: 'Đã xảy ra lỗi. Vui lòng thử lại.', hotIndustries: 'Xu hướng nghề nghiệp', dailyQuote: 'Cảm Hứng Mỗi Ngày', chatHistory: 'Lịch sử trò chuyện', switchToVoice: 'Chuyển sang hội thoại', newChat: 'Cuộc trò chuyện mới', footerDisclaimer: 'AI có thể gây ra sai sót, mọi thông tin chỉ mang tính chất tham khảo, quyền quyết định thuộc về bạn.', thinking: 'Đang suy nghĩ...', thinkingPassions: 'Đang khám phá đam mê của bạn...', thinkingOpportunities: 'Đang phân tích cơ hội nghề nghiệp...', thinkingMarket: 'Đang nghiên cứu thị trường lao động...', thinkingProfile: 'Đang đánh giá hồ sơ của bạn...', thinkingPaths: 'Đang tìm kiếm lộ trình học tập...', profileName: 'Họ và tên', careerGoal: 'Mục tiêu sự nghiệp', prefLang: 'Ngôn ngữ ưu tiên', langName: 'Tiếng Việt', langEn: 'Tiếng Anh', langVi: 'Tiếng Việt', saveChanges: 'Lưu thay đổi', guestMode: 'Chế độ khách', guest: 'Khách', undecided: 'Chưa xác định', exploring: 'Đang khám phá', selectMic: 'Chọn Micro', transcript: 'Hội thoại trực tiếp', aiBusy: 'Hệ thống AI đang bận do lượng yêu cầu cao. Vui lòng đợi giây lát và thử lại.', failedRoadmapFormat: 'Không thể tạo định dạng lộ trình.', noAiResponse: 'Không có phản hồi từ AI.', failedToCommunicate: 'Không thể kết nối với máy chủ.', noExternalResponse: 'Không có phản hồi từ mô hình bên ngoài.', mediaNotSupported: 'API MediaDevices không được hỗ trợ. Vui lòng sử dụng HTTPS.', connectionFailed: 'Kết nối thất bại. Vui lòng kiểm tra mạng hoặc thử lại.', tempChatTooltip: 'Tin nhắn trò chuyện tạm thời sẽ không được lưu vào lịch sử.', temporaryChat: 'Trò chuyện tạm thời', uploadFile: 'Tải tệp lên', takePhoto: 'Chụp ảnh', live: 'Trực tiếp', readyToStart: 'Sẵn sàng bắt đầu', universityScores: 'Tra cứu điểm chuẩn', careerCompare: 'So sánh ngành nghề', trendingCareers: 'Nghề Hot VN 2026', mockInterview: 'Phỏng vấn thử', promptBuilder: 'Mẫu & Tạo Prompt AI', careerLifecycle: 'Vòng đời sự nghiệp', monetizationPartners: 'Gói cước & Đối tác',
    
    // Auth - Forgot Password
    resetPasswordTitle: 'Đặt lại Mật khẩu',
    resetPasswordDesc: 'Nhập địa chỉ email của bạn và chúng tôi sẽ gửi hướng dẫn đặt lại mật khẩu.',
    sendLink: 'Gửi liên kết',
    backToLogin: 'Quay lại đăng nhập',
    linkSent: 'Thành công! Vui lòng kiểm tra email của bạn để lấy liên kết.',

    // AI Config
    aiConfigTitle: 'Cấu hình Mô hình AI',
    aiProvider: 'Nhà cung cấp AI',
    providerGemini: 'CareerGuide AI',
    providerCustom: 'Tùy chỉnh (OpenAI)',
    providerN8N: 'n8n Workflow',
    endpointUrl: 'Đường dẫn Endpoint',
    n8nWebhookUrl: 'n8n Webhook URL (POST)',
    endpointNote: 'Tương thích với Ollama, vLLM, hoặc LM Studio.',
    n8nNote: 'Yêu cầu Webhook (POST) trả về JSON có thuộc tính "output" hoặc "text".',
    modelName: 'Tên Mô hình',
    
    // New Translations
    chatPlaceholder: 'Hỏi tôi bất cứ điều gì về sự nghiệp của bạn...',
    heroBadge: 'Định hướng bằng AI',
    heroTitlePrefix: 'Định hướng cho ',
    heroTitleSuffix: 'mọi người',
    hotIndustriesTitle: 'Đón Đầu Tương Lai',
    hotIndustriesSub: 'Khám phá các ngành nghề tăng trưởng cao tại Việt Nam, nơi AI của chúng mình có thể giúp bạn định hướng và tìm được công việc mơ ước.',
    vnLaborMarketTitle: 'Thị Trường Lao Động VN 2024-2025',
    vnLaborMarketDesc: 'Nhu cầu nhân lực chất lượng cao trong mảng Công nghệ (AI, Bán dẫn), Logistics và Năng lượng tái tạo đang tăng vọt.',
    placeholderName: 'Nguyễn Văn A',
    placeholderEmail: 'ten@example.com',
    placeholderPassword: '••••••••',
    placeholderSearch: 'Tìm kiếm...',
    placeholderCareerGoal: 'Mục tiêu nghề nghiệp của bạn...',
    placeholderPortfolioTitle: 'Tên mục, chứng chỉ hoặc dự án...',
    placeholderPortfolioDesc: 'Mô tả ngắn gọn về thành tích của bạn...',
    placeholderPortfolioScore: 'Điểm số, GPA hoặc kết quả...',
    placeholderPortfolioDate: '2023 - 2024',
    placeholderMessage: 'Nhập tin nhắn...',
    placeholderResetCode: 'Nhập mã 8 chữ số...',
    placeholderNewPassword: 'Mật khẩu mới',
    placeholderConfirmPassword: 'Xác nhận mật khẩu mới',
    placeholderAdvice: 'Bạn có lời khuyên nào cho tôi không?',
    placeholderBio: 'Kể một chút về bản thân bạn...',
    careerQuizTitle: 'Trắc Nghiệm Nghề Nghiệp',
    careerQuizDesc: 'Khám phá nhóm tính cách nghề nghiệp của bạn (RIASEC) chỉ trong 2 phút.',
    accuracyRate: 'Tỉ lệ chính xác AI',
    userCount: 'Người dùng tin tưởng',
    activeSessions: 'Phiên tư vấn 24h',
    accuracyValue: '98.5%',
    userValue: '12,500+',
    sessionValue: '1,240',
    dashboard: 'Dashboard',
    growthRate: 'Tỉ lệ tăng trưởng',
    empoweringFutures: 'Kiến tạo tương lai',
    backToHome: 'Quay lại Trang chủ',
    noResultsFound: 'Không tìm thấy kết quả',
    generateRoadmap: 'Tạo lộ trình nghề nghiệp',
    basedOnHistory: 'Dựa trên lịch sử trò chuyện của bạn',
    enterNewPassword: 'Nhập mật khẩu mới của bạn bên dưới.',
    enterResetCode: 'Nhập mã 8 chữ số đã được gửi đến email của bạn.',
    updatePassword: 'Cập nhật mật khẩu',
    verifyCode: 'Xác minh mã',
    sendVerificationCode: 'Gửi mã xác minh',
    codeSent: 'Mã đã được gửi!',
    verificationCode: 'Mã xác minh',
    resendCode: 'Gửi lại mã / Thay đổi email',
    fullName: 'Họ và tên',
    newPassword: 'Mật khẩu mới',
    confirmPassword: 'Xác nhận mật khẩu',
    attach: 'Đính kèm',
    close: 'Đóng',
    fillAllFields: 'Vui lòng điền đầy đủ các trường',
    emailRegistered: 'Email đã được đăng ký',
    invalidLogin: 'Email hoặc mật khẩu không hợp lệ',
    firebaseNotConfigured: 'Firebase chưa được cấu hình. Vui lòng kiểm tra console.',
    loginFailed: 'Đăng nhập thất bại:',
    enterEmail: 'Vui lòng nhập email của bạn',
    googleLoginRequired: 'Tài khoản này sử dụng Đăng nhập Google. Vui lòng đăng nhập bằng Google.',
    emailNotFound: 'Không tìm thấy email. Vui lòng đăng ký tài khoản trước.',
    failedToSendEmail: 'Gửi email thất bại. Vui lòng kiểm tra kết nối internet hoặc thử lại sau.',
    invalidCode: 'Mã xác minh không hợp lệ.',
    passwordsDoNotMatch: 'Mật khẩu không khớp',
    userNotFound: 'Không tìm thấy người dùng.',
    passwordUpdated: 'Cập nhật mật khẩu thành công! Vui lòng đăng nhập.',
    profileSaved: 'Đã lưu cài đặt!',
    chatCleared: 'Đã xóa lịch sử trò chuyện',
    sessionCleared: 'Đã xóa phiên trò chuyện hiện tại',
    imageTooLarge: 'Kích thước ảnh phải nhỏ hơn 5MB.',
    invalidImage: 'Vui lòng chọn một tệp hình ảnh hợp lệ.',
    cameraDenied: 'Không thể truy cập máy ảnh.',
    failedToLoadImage: 'Không thể tải hình ảnh.',
    failedToReadFile: 'Không thể đọc tệp.',
    failedToSaveProfile: 'Không thể lưu hồ sơ. Ảnh có thể quá lớn.',
    roadmapUpdated: 'Đã cập nhật lộ trình thành công!',
    loginToSetGoal: 'Vui lòng đăng nhập để thiết lập mục tiêu sự nghiệp.',
    syncToProgress: 'Đồng bộ vào Tiến độ',
    pasted: 'ĐÃ DÁN',
    microphone: 'Microphone', startListening: 'Bắt đầu nghe', stopListening: 'Dừng nghe', voiceInput: 'Nhập bằng giọng nói',
    failedToGenerateRoadmap: 'Không thể tạo lộ trình. Vui lòng thử lại.',
    preparingPDF: 'Đang chuẩn bị bản PDF của bạn...',
    pdfExportSuccess: 'Xuất PDF thành công!',
    exportFailed: 'Xuất file thất bại. Vui lòng thử lại.',
    generatingImage: 'Đang tạo ảnh...',
    imageSaveSuccess: 'Lưu ảnh thành công!',
    imageSaveFailed: 'Lưu ảnh thất bại. Vui lòng thử lại.',
    statusDone: 'Hoàn thành',
    statusInProgress: 'Đang thực hiện',
    statusTodo: 'Chưa bắt đầu',
    roadmapEmptyTitle: 'Bảng Tiến Độ Đang Trống',
    roadmapEmptyDesc: 'Hãy trò chuyện với AI trước để hệ thống hiểu rõ mục tiêu của bạn và tạo ra một lộ trình nghề nghiệp cá nhân hóa.',
    startChatting: 'Bắt đầu trò chuyện',
    generating: 'Đang tạo lộ trình...',
    generateRoadmapNow: 'Tạo Lộ Trình Ngay',
    careerRoadmap: 'Bảng Tiến Độ',
    roadmapSub: 'Theo dõi tiến độ và xuất file để chia sẻ với phụ huynh, giáo viên.',
    saveImage: 'Lưu Ảnh',
    exportPDF: 'Xuất PDF',
    personalProfile: 'Hồ sơ cá nhân',
    progressBoardTitle: 'Bảng Đánh Giá Tiến Độ',
    progressBoardSub: 'Nhấn vào từng mục để cập nhật trạng thái',
    addNotePlaceholder: 'Thêm ghi chú hoặc đánh giá...',
    generatedBy: 'Tạo bởi CareerGuide AI',
    dateLabel: 'Ngày xuất:',
    generatingDocument: 'Đang Tạo Tài Liệu',
    preparingFile: 'Vui lòng đợi trong giây lát, hệ thống đang xử lý...',
    save: 'Lưu',
    cancel: 'Hủy',
    delete: 'Xóa',
    enterTitleError: 'Vui lòng nhập tiêu đề',
    itemAdded: 'Đã thêm mục vào hồ sơ',
    itemRemoved: 'Đã xóa mục',
    pdfFilename: 'Lo-Trinh-Nghe-Nghiep.pdf',
    imageFilename: 'Lo-Trinh-Nghe-Nghiep.png',
    quizResultTitle: 'Kết Quả Trắc Nghiệm Của Bạn',
    quizAdvicePrompt: 'Tôi vừa hoàn thành bài trắc nghiệm RIASEC và kết quả của tôi là {{result}}. Bạn có thể cho tôi lời khuyên nghề nghiệp dựa trên kết quả này không?',
    retakeQuiz: 'Làm lại trắc nghiệm',
    discussWithAI: 'Thảo luận với AI',
    question: 'Câu hỏi',
    of: '/',
    quizNo: 'Không thích',
    quizMaybe: 'Tạm được',
    quizYes: 'Rất thích',
    quizRealistic: 'Thực tế (Realistic): Bạn là người thực tế, thích làm việc với đôi tay và công cụ.',
    quizInvestigative: 'Nghiên cứu (Investigative): Bạn có tư duy phân tích, tò mò và thích giải quyết vấn đề.',
    quizArtistic: 'Nghệ thuật (Artistic): Bạn sáng tạo, giàu trí tưởng tượng và thích thể hiện bản thân.',
    quizSocial: 'Xã hội (Social): Bạn thích giúp đỡ, giảng dạy và làm việc với con người.',
    quizEnterprising: 'Quản lý (Enterprising): Bạn đầy tham vọng, có khả năng lãnh đạo và thuyết phục.',
    quizConventional: 'Nghiệp vụ (Conventional): Bạn ngăn nắp, tỉ mỉ và thích làm việc với dữ liệu.',
    quizQ1: 'Mình thích làm việc với động vật, công cụ hoặc máy móc.',
    quizQ2: 'Mình thích giải các bài toán và vấn đề khoa học.',
    quizQ3: 'Mình thích các hoạt động sáng tạo như nghệ thuật, kịch hoặc âm nhạc.',
    quizQ4: 'Mình thích giúp đỡ, dạy bảo hoặc cung cấp dịch vụ cho người khác.',
    quizQ5: 'Mình thích lãnh đạo và thuyết phục mọi người.',
    quizQ6: 'Mình thích làm việc với con số, hồ sơ hoặc máy móc một cách ngăn nắp.',
    quizQ7: 'Mình thích sửa chữa đồ đạc.',
    quizQ8: 'Mình thích thực hiện các thí nghiệm.',
    quizQ9: 'Mình thích viết truyện hoặc làm thơ.',
    quizQ10: 'Mình thích tình nguyện cho các hoạt động xã hội.',
    quizQ11: 'Mình thích bắt đầu công việc kinh doanh riêng.',
    quizQ12: 'Mình thích sắp xếp dữ liệu và hồ sơ.',
    continueJourney: 'Sẵn sàng tiếp tục hành trình,',
    goToDashboard: 'Vào Dashboard',
    guestSession: 'Phiên Khách',
    logout: 'Đăng xuất',
    chooseAvatar: 'Chọn Ảnh Đại Diện',
    randomAvatar: 'Ảnh Ngẫu Nhiên',
    searchChats: 'Tìm kiếm cuộc trò chuyện...',
    collapseSidebar: 'Thu gọn thanh bên',
    expandSidebar: 'Mở rộng thanh bên',
    progress: 'Tiến độ',
    scholarships: 'Học bổng',
    findScholarships: 'Tìm Học bổng',
    scholarshipDesc: 'Khám phá các chương trình học bổng và hỗ trợ tài chính phù hợp với hồ sơ và mục tiêu của bạn nhờ trí tuệ nhân tạo.',
    scholarshipSearchPlaceholder: 'VD: Học bổng kỹ thuật IT ở Mỹ dành cho sinh viên đại học...',
    storageManagement: 'Quản lý Dữ liệu',
    manageChatData: 'Quản lý dữ liệu trò chuyện của bạn',
    clearAllHistory: 'Xóa tất cả lịch sử',
    clearHistoryConfirm: 'Bạn có chắc chắn muốn xóa tất cả lịch sử trò chuyện? Hành động này không thể hoàn tác.',
    streakTooltip: 'Chuỗi {{streak}} ngày hoàn thành nhiệm vụ!',

    // Portfolio
    portfolio: 'Hồ sơ cá nhân',
    portfolioDesc: 'Lưu trữ chứng chỉ, điểm số và các dự án cá nhân. Dễ dàng trích xuất thành một CV/Portfolio hoàn chỉnh khi nộp hồ sơ xét tuyển.',
    addPortfolioItem: 'Thêm mục mới',
    itemType: 'Loại',
    typeCertificate: 'Chứng chỉ',
    typeGrade: 'Điểm số / Thành tích học tập',
    typeProject: 'Dự án cá nhân',
    itemTitle: 'Tiêu đề',
    itemDesc: 'Mô tả chi tiết',
    itemDate: 'Thời gian',
    itemScore: 'Điểm số / Kết quả',
    itemLink: 'Đường dẫn (Tùy chọn)',
    exportCV: 'Xuất CV/Portfolio',
    noPortfolioItems: 'Chưa có mục nào trong hồ sơ của bạn. Hãy thêm thành tích để xây dựng CV nhé!',

    // Feature Translations - UPDATED
    featureVoiceTitle: 'Tư vấn 1-1 Trực tiếp',
    featureVoiceDesc: 'Trò chuyện thoại với AI như một cố vấn học tập thực thụ. Nhận phản hồi và định hướng ngay lập tức.',
    feature247Title: 'Luôn sẵn sàng 24/7',
    feature247Desc: 'Không cần đặt hẹn. Không phải chờ đợi. Lời khuyên sự nghiệp bất cứ khi nào bạn cần.',
    featureScanTitle: 'Phân tích Hồ sơ học tập',
    featureScanDesc: 'Phân tích điểm số và hoạt động ngoại khóa bằng AI để gợi ý khối thi và ngành học phù hợp.',
    featureRoadmapTitle: 'Lộ trình Cá nhân hóa',
    featureRoadmapDesc: 'Từ việc xác định thế mạnh đến việc chọn ngành học, chúng tôi vạch ra lộ trình dành riêng cho bạn.',
    featureHeader: 'Cách hướng nghiệp',
    featureHeaderHighlight: 'nên',
    featureHeaderSuffix: 'được thực hiện từ lâu.',
    featureSub: 'Một nền tảng thay thế các chuyên gia đắt đỏ và việc tìm kiếm thông tin rời rạc.',

    systemInstruction: 'Bạn là chuyên gia tư vấn hướng nghiệp dành riêng cho học sinh THPT tên là Career Guide AI. Nhiệm vụ của bạn là giúp học sinh xác định thế mạnh, chọn khối thi, ngành học và trường đại học phù hợp tại Việt Nam. Mục tiêu của bạn là hỗ trợ tận tâm và chính xác nhất. Hãy trả lời câu hỏi trực tiếp, tự nhiên, thân thiện và thấu hiểu. KHÔNG xuất ra các khối JSON câu hỏi làm rõ (clarification). CHỈ khi người dùng yêu cầu lập lộ trình, kế hoạch hoặc yêu cầu cập nhật bảng tiến độ, bạn mới cung cấp lộ trình phát triển trong 3 tháng dưới dạng khối JSON như sau: ```json [{"id": "1", "title": "Tháng 1: Bước 1", "description": "Chi tiết cho tháng 1", "status": "todo"}] ```. KHÔNG bao gồm khối JSON này trong các cuộc trò chuyện thông thường trừ khi được yêu cầu cụ thể. Lộ trình PHẢI được giới hạn trong khoảng thời gian là 3 tháng, tránh các kế hoạch quá dài hạn. Hãy trả lời chuyên nghiệp, khích lệ và súc tích. Nếu có kết quả RIASEC, hãy dựa vào đó để tư vấn. CHỈ sử dụng tiếng Anh và tiếng Việt.',
    voiceSystemInstruction: 'Bạn là chuyên gia tư vấn hướng nghiệp Career Compass AI. QUY TẮC BẮT BUỘC: 1. Chỉ trả lời 100% bằng tiếng Việt tự nhiên, ấm áp, thân thiện như người anh/chị cố vấn. 2. TUYỆT ĐỐI KHÔNG xuất ra bất kỳ suy nghĩ nội bộ nào, KHÔNG có tiêu đề tiếng Anh ("Confirming...", "Analyzing..."), KHÔNG pha trộn tiếng Anh. 3. Trả lời ngay tức thì bằng 1-2 câu súc tích (dưới 35 từ), đi thẳng vào trọng tâm hướng nghiệp. 4. Không dùng ký hiệu markdown hay hoa thị (*).',

    // Terms of Service
    termsTitle: 'Điều khoản Dịch vụ & Tuyên bố miễn trừ trách nhiệm',
    terms1: '1. Chấp nhận Điều khoản:',
    terms1Desc: 'Bằng cách sử dụng CareerGuide AI, bạn đồng ý với các điều khoản này.',
    terms2: '2. Hạn chế của AI:',
    terms2Desc: 'Lời khuyên nghề nghiệp được cung cấp bởi Trí tuệ Nhân tạo. Nó có thể chứa lỗi, thông tin không chính xác hoặc lỗi thời.',
    terms3: '3. Không chịu trách nhiệm chuyên môn:',
    terms3Desc: 'Công cụ này chỉ dành cho mục đích giáo dục và cung cấp thông tin. Nó không thay thế cho tư vấn nghề nghiệp, pháp lý hoặc tài chính chuyên nghiệp.',
    terms4: '4. Quyền riêng tư dữ liệu:',
    terms4Desc: 'Chúng tôi tôn trọng quyền riêng tư của bạn. Hình ảnh tải lên và nhật ký trò chuyện được xử lý an toàn nhưng vui lòng tránh chia sẻ thông tin cá nhân quá nhạy cảm.',
    terms5: '5. Trách nhiệm của người dùng:',
    terms5Desc: 'Bạn hoàn toàn chịu trách nhiệm về bất kỳ quyết định nào được đưa ra dựa trên các đề xuất của AI.',
    placeholderCode: '00000000',
    welcomePhrases: [
      "Hãy chia sẻ ý tưởng của bạn nhé!",
      "Hôm nay bạn đang nghĩ gì?",
      "Cùng khám phá tương lai của bạn nào!",
      "Sẵn sàng tìm kiếm sự nghiệp mơ ước chưa?"
    ],
    laborMarketTags: [
      { en: 'AI Engineer', vi: 'Kỹ sư AI' },
      { en: 'Logistics Manager', vi: 'Quản lý Logistics' },
      { en: 'Semiconductor Tech', vi: 'Kỹ thuật Bán dẫn' },
      { en: 'Green Energy', vi: 'Năng lượng xanh' }
    ],
    termsAccept: 'Tôi Đã Hiểu & Đồng Ý'
  }
};
