import { GoogleGenAI, Modality } from "@google/genai";
import type { LiveServerMessage } from "@google/genai";
import { TRANSLATIONS } from "../constants";
import { Language, AIProvider, UserProfile } from "../types";
import { downsampleBuffer } from "../utils/audio";

// Helper to strip markdown asterisks (*, **) and formatting artifacts from strings and objects
export const cleanMarkdownAsterisks = (val: any): any => {
  if (typeof val === 'string') {
    return val
      .replace(/\*\*([^*]+)\*\*/g, '$1') // remove **bold**
      .replace(/\*([^*]+)\*/g, '$1')     // remove *italic*
      .replace(/^\s*[\*]\s+/gm, '• ')   // replace list item asterisks with clean bullet points
      .replace(/\*/g, '')                // remove remaining stray asterisks
      .trim();
  }
  if (Array.isArray(val)) {
    return val.map(cleanMarkdownAsterisks);
  }
  if (val && typeof val === 'object') {
    const cleaned: any = {};
    for (const key of Object.keys(val)) {
      cleaned[key] = cleanMarkdownAsterisks(val[key]);
    }
    return cleaned;
  }
  return val;
};

// Helper to strip markdown asterisks and any English thinking/reasoning prefixes from voice model outputs
export const cleanVoiceModelOutput = (rawText: string, language: Language = Language.VI): string => {
  if (!rawText || typeof rawText !== 'string') return '';

  let text = rawText.trim();

  // 1. Remove XML/HTML thought tags (<thought>...</thought>, <reasoning>...</reasoning>, etc.)
  text = text.replace(/<(thought|reasoning|think)>[\s\S]*?<\/\1>/gi, '');

  // 2. Remove markdown bold headers often generated by LLM reasoning like **Confirming Potential Directions**, **Analysis**, etc.
  text = text.replace(/^\s*\*\*([^*]+)\*\*\s*/i, '');
  text = text.replace(/\*\*([A-Za-z0-9\s:_-]+)\*\*/g, '');

  // 3. If target language is Vietnamese, eliminate any English reasoning preamble that precedes Vietnamese sentences
  if (language === Language.VI) {
    const viDiacriticsMatch = text.match(/[àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđÀÁẠẢÃÂẦẤẬẨẪĂẰẮẶẲẴÈÉẸẺẼÊỀẾỆỂỄÌÍỊỈĨÒÓỌỎÕÔỒỐỘỔỖƠỜỚỢỞỠÙÚỤỦŨƯỪỨỰỬỮỲÝỴỶỸĐ]/);
    if (viDiacriticsMatch && viDiacriticsMatch.index !== undefined && viDiacriticsMatch.index > 0) {
      const prefix = text.substring(0, viDiacriticsMatch.index);
      const isEnglishMeta = /(?:I'm|I am|I will|My goal|user|profile|affirm|recommendation|persona|solidify|rationale|thinking|confirming|direction|clarifying)/i.test(prefix);
      if (isEnglishMeta) {
        const lastPeriod = prefix.lastIndexOf('. ');
        if (lastPeriod !== -1) {
          text = text.substring(lastPeriod + 2);
        } else {
          const lastSpace = prefix.lastIndexOf(' ');
          text = text.substring(lastSpace !== -1 ? lastSpace + 1 : viDiacriticsMatch.index);
        }
      }
    }
  }

  return cleanMarkdownAsterisks(text);
};

// Helper for exponential backoff retry
const retryWithBackoff = async <T>(
  fn: () => Promise<T>,
  maxRetries: number = 3,
  initialDelay: number = 1000
): Promise<T> => {
  let lastError: any;
  for (let i = 0; i < maxRetries; i++) {
    try {
      return await fn();
    } catch (error: any) {
      lastError = error;
      const isRetryable = 
        error.message?.includes('503') || 
        error.message?.includes('high demand') ||
        error.message?.includes('UNAVAILABLE') ||
        error.message?.includes('overloaded');
        
      if (!isRetryable || i === maxRetries - 1) throw error;
      
      const delay = initialDelay * Math.pow(2, i);
      console.warn(`Gemini API busy (503). Retrying in ${delay}ms... (Attempt ${i + 1}/${maxRetries})`);
      await new Promise(resolve => setTimeout(resolve, delay));
    }
  }
  throw lastError;
};

// Client-side fallback if user provided custom API Key directly in Settings
const generateClientContentWithFallback = async (
    aiInstance: GoogleGenAI,
    options: {
        model?: string;
        contents: any;
        config?: any;
    }): Promise<any> => {
    const defaultModels = [
        "gemini-3.6-flash",
        "gemini-2.5-flash",
        "gemini-2.5-flash-lite",
        "gemini-3.6-flash",
        "gemini-3.6-flash-lite"
    ];
    const modelsToTry = options.model ? [options.model, ...defaultModels] : defaultModels;
    const uniqueModels = Array.from(new Set(modelsToTry));

    let lastError: any = null;

    if (options.config?.tools && options.config.tools.length > 0) {
        for (const model of uniqueModels) {
            try {
                const response = await aiInstance.models.generateContent({
                    model: model,
                    contents: options.contents,
                    config: options.config
                });
                return response;
            } catch (error: any) {
                lastError = error;
            }
        }
    }

    const configWithoutTools = { ...options.config };
    if (configWithoutTools.tools) {
        delete configWithoutTools.tools;
    }

    for (const model of uniqueModels) {
        try {
            const response = await aiInstance.models.generateContent({
                model: model,
                contents: options.contents,
                config: configWithoutTools
            });
            return response;
        } catch (error: any) {
            lastError = error;
        }
    }

    throw lastError || new Error("All client model fallback attempts exhausted / Tất cả các phương án kết nối mô hình đều thất bại.");
};

export const getGeminiApiKeysPool = (userProfile?: UserProfile | null): string[] => {
  const keys: string[] = [];
  const add = (k?: string | null) => {
    if (!k) return;
    const parts = k.split(/[\n,;]+/).map(p => p.trim()).filter(p => p.length > 10);
    for (const p of parts) {
      if (!keys.includes(p)) keys.push(p);
    }
  };

  // Built-in system key (Embedded directly, ready to use out-of-the-box)
  const SYSTEM_KEY_B64 = "QVEuQWI4Uk42S1Y0Szh5YUNBdjNwaWlkbUtpV2d3aW55WFhnc0l2dlFsekZTcVBONnpVU1E=";
  try {
    if (typeof atob === 'function') {
      add(atob(SYSTEM_KEY_B64));
    }
  } catch (e) {}

  add(userProfile?.customGeminiApiKey);
  try {
    add(localStorage.getItem('custom_gemini_api_key'));
    add(localStorage.getItem('gemini_api_keys'));
    add(localStorage.getItem('gemini_api_key'));
    add(localStorage.getItem('custom_api_key'));
    add(localStorage.getItem('ai_api_key'));
  } catch (e) {}

  add(import.meta.env?.VITE_GEMINI_API_KEYS as string);
  add(import.meta.env?.VITE_GEMINI_API_KEY as string);
  add(process.env?.GEMINI_API_KEY as string);

  return keys;
};

export const getGeminiApiKey = (userProfile?: UserProfile | null): string => {
  const pool = getGeminiApiKeysPool(userProfile);
  if (pool.length === 0) return '';
  const idx = Math.floor(Math.random() * pool.length);
  return pool[idx] || pool[0];
};

export const cleanFrontEndErrorMessage = (error: any, language: Language): string => {
  const errMsg = error?.message || String(error);
  const isVi = language === Language.VI;
  
  if (errMsg.includes("API key not valid") || errMsg.includes("API_KEY_INVALID") || errMsg.includes("API key must be set") || errMsg.includes("invalid authentication credentials") || errMsg.includes("OAuth 2") || errMsg.includes("401") || errMsg.includes("403")) {
    return isVi 
      ? "Hệ thống AI đang được bảo trì kết nối hoặc cập nhật dữ liệu. Vui lòng gửi lại yêu cầu sau giây lát."
      : "The AI system is currently synchronizing. Please retry in a moment.";
  }
  if (errMsg.includes("RESOURCE_EXHAUSTED") || errMsg.includes("429") || errMsg.includes("quota") || errMsg.includes("Quota exceeded")) {
    return isVi 
      ? "Hệ thống AI đang tạm thời đạt giới hạn lượt hỏi. Vui lòng gửi lại sau vài giây nhé!"
      : "The AI service has temporarily reached its limit. Please try again in a few seconds!";
  }
  if (errMsg.includes("503") || errMsg.includes("overloaded") || errMsg.includes("busy") || errMsg.includes("UNAVAILABLE")) {
    return isVi 
      ? "Hệ thống AI hiện đang xử lý nhiều yêu cầu, vui lòng ấn gửi lại sau giây lát."
      : "The AI model is currently busy. Please retry in a moment.";
  }
  try {
    const parsed = JSON.parse(errMsg);
    if (parsed.error && parsed.error.message) {
      const msg = parsed.error.message;
      if (msg.includes("API key not valid") || msg.includes("API_KEY_INVALID") || msg.includes("API key must be set") || msg.includes("401") || msg.includes("403")) {
        return isVi 
          ? "Hệ thống AI đang được bảo trì kết nối hoặc cập nhật dữ liệu. Vui lòng gửi lại yêu cầu sau giây lát."
          : "The AI system is currently synchronizing. Please retry in a moment.";
      }
      if (msg.includes("RESOURCE_EXHAUSTED") || msg.includes("quota") || msg.includes("Quota exceeded") || msg.includes("429")) {
        return isVi 
          ? "Hệ thống AI đang tạm thời đạt giới hạn lượt hỏi. Vui lòng gửi lại sau vài giây nhé!"
          : "The AI service has temporarily reached its limit. Please try again in a few seconds!";
      }
      if (msg.includes("503") || msg.includes("overloaded") || msg.includes("busy") || msg.includes("UNAVAILABLE")) {
        return isVi 
          ? "Hệ thống AI hiện đang xử lý nhiều yêu cầu, vui lòng ấn gửi lại sau giây lát."
          : "The AI model is currently busy. Please retry in a moment.";
      }
      return msg;
    }
  } catch (e) {
    // No-op
  }
  return errMsg;
};

// Generic helper to call AI with prompt via backend proxy or client fallback
export const requestAiContent = async (
  prompt: string,
  systemInstruction: string = "You are a helpful assistant. Do not use asterisks (*) in text formatting.",
  language: Language = Language.VI
): Promise<string> => {
  const keysPool = getGeminiApiKeysPool();
  const activeKey = getGeminiApiKey();

  const callApi = async () => {
    let lastError: any = null;
    try {
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          history: [],
          message: prompt,
          systemInstruction,
          apiKey: activeKey || undefined
        })
      });

      const contentType = response.headers.get('content-type');
      const isJson = contentType && contentType.includes('application/json');

      if (isJson) {
        const resData = await response.json();
        if (response.ok && resData.text) {
          const cleaned = cleanMarkdownAsterisks(resData.text);
          if (cleaned && cleaned !== "{}" && cleaned !== "[]") {
            return cleaned;
          }
        }
        if (resData.error) {
          throw new Error(resData.error);
        }
      }
      if (!response.ok) {
        throw new Error(`Server HTTP ${response.status}`);
      }
    } catch (e: any) {
      if (e?.message && e.message.includes("Chưa cấu hình khóa API")) {
        throw e;
      }
      lastError = e;
      console.warn("Backend chat proxy error, checking client fallback:", e);
    }

    // Direct Client Custom Key Execution across available keys
    const candidateKeys = keysPool.length > 0 ? keysPool : (activeKey ? [activeKey] : []);
    for (const key of candidateKeys) {
      try {
        const ai = new GoogleGenAI({ apiKey: key });
        const aiResponse = await generateClientContentWithFallback(ai, {
          model: 'gemini-3.6-flash',
          contents: [{ role: 'user', parts: [{ text: prompt }] }],
          config: { systemInstruction }
        });
        if (aiResponse.text) {
          const cleaned = cleanMarkdownAsterisks(aiResponse.text);
          if (cleaned && cleaned !== "{}" && cleaned !== "[]") {
            return cleaned;
          }
        }
      } catch (err: any) {
        lastError = err;
      }
    }

    if (lastError) {
      throw lastError;
    }

    throw new Error(language === Language.VI ? "Lỗi kết nối AI: Không nhận được phản hồi từ mô hình." : "AI connection error: No response from model.");
  };

  try {
    return await retryWithBackoff(callApi);
  } catch (error: any) {
    throw new Error(cleanFrontEndErrorMessage(error, language));
  }
};

// Ultra-fast dedicated Voice AI response synthesizer for minimum conversational latency
export const requestVoiceAiFastResponse = async (
  userSpeech: string,
  systemInstruction: string,
  language: Language = Language.VI,
  userProfile?: UserProfile | null
): Promise<string> => {
  const keysPool = getGeminiApiKeysPool(userProfile);
  const activeKey = getGeminiApiKey(userProfile);

  const voicePrompt = language === Language.VI
    ? `${systemInstruction}\n\n[QUY TẮC PHẢN HỒI THOẠI]: 1. Chỉ trả lời 100% bằng tiếng Việt tự nhiên, ấm áp, thân thiện. 2. TUYỆT ĐỐI KHÔNG xuất ra bất kỳ suy nghĩ nội bộ nào, KHÔNG có tiêu đề tiếng Anh ("Confirming...", "Analyzing..."), KHÔNG pha trộn tiếng Anh. 3. Trả lời ngay lập tức trong 1-2 câu ngắn gọn (dưới 35 từ), đi thẳng vào trọng tâm câu hỏi của học sinh.\n\nHọc sinh vừa nói: "${userSpeech}"`
    : `${systemInstruction}\n\n[VOICE RULES]: 1. Respond 100% in English naturally and warmly. 2. NEVER output internal thoughts or English headers. 3. Answer immediately in 1-2 concise sentences (under 35 words).\n\nStudent said: "${userSpeech}"`;

  // 1. Direct Client-side generation for lowest round-trip latency
  const candidateKeys = keysPool.length > 0 ? keysPool : (activeKey ? [activeKey] : []);
  for (const key of candidateKeys) {
    try {
      const ai = new GoogleGenAI({ apiKey: key });
      const fastModels = ['gemini-2.5-flash', 'gemini-3.6-flash-lite', 'gemini-3.6-flash'];
      for (const model of fastModels) {
        try {
          const resp = await ai.models.generateContent({
            model,
            contents: [{ role: 'user', parts: [{ text: voicePrompt }] }],
            config: {
              systemInstruction,
              maxOutputTokens: 90,
              temperature: 0.5
            }
          });
          if (resp.text) {
            const cleaned = cleanVoiceModelOutput(resp.text, language);
            if (cleaned && cleaned !== "{}" && cleaned !== "[]" && cleaned.length > 2) {
              return cleaned;
            }
          }
        } catch (mErr) {
          // continue
        }
      }
    } catch (kErr) {
      // continue
    }
  }

  // 2. Fallback to /api/chat
  try {
    const res = await requestAiContent(voicePrompt, systemInstruction, language);
    return cleanVoiceModelOutput(res, language);
  } catch (err) {
    throw err;
  }
};

export const generateRoadmap = async (
  chatHistory: { role: string; text: string }[],
  language: Language,
  userProfile?: UserProfile | null
) => {
  const isVi = language === Language.VI;
  const fallbackRoadmap = isVi ? [
    {
      id: "rm-step-1",
      title: "Khám phá bản thân & Đánh giá năng lực RIASEC",
      description: "Hoàn thành bài trắc nghiệm tính cách nghề nghiệp, xác định các nhóm đặc điểm nổi trội và lĩnh vực quan tâm hàng đầu.",
      status: "todo"
    },
    {
      id: "rm-step-2",
      title: "Khảo sát ngành nghề & Phân tích thị trường tuyển dụng",
      description: "Tìm hiểu 3 vị trí việc làm thực tế, tra cứu điểm chuẩn đại học và tìm hiểu yêu cầu kỹ năng đầu vào.",
      status: "todo"
    },
    {
      id: "rm-step-3",
      title: "Học tập nền tảng & Tích lũy kỹ năng cốt lõi",
      description: "Tham gia khóa học cơ bản trực tuyến, rèn luyện tư duy logic và kỹ năng tiếng Anh chuyên ngành.",
      status: "todo"
    },
    {
      id: "rm-step-4",
      title: "Xây dựng Portfolio & Thực hành phỏng vấn thử",
      description: "Tạo CV chuẩn chỉnh, hoàn thành 01 mini-project thực tế và luyện tập trả lời phỏng vấn HR cùng AI.",
      status: "todo"
    }
  ] : [
    {
      id: "rm-step-1",
      title: "Self-Discovery & RIASEC Assessment",
      description: "Complete career orientation tests, identify primary strengths and top focus interest areas.",
      status: "todo"
    },
    {
      id: "rm-step-2",
      title: "Industry Survey & Job Market Research",
      description: "Explore 3 potential career paths, check university requirements, and analyze job descriptions.",
      status: "todo"
    },
    {
      id: "rm-step-3",
      title: "Core Skill Building & Online Coursework",
      description: "Enroll in foundational online courses, develop analytical thinking and domain communication.",
      status: "todo"
    },
    {
      id: "rm-step-4",
      title: "Portfolio Development & Mock Interview Practice",
      description: "Build a polished CV, complete a practical mini-project, and practice interview questions with AI.",
      status: "todo"
    }
  ];

  const prompt = language === Language.EN
    ? `Based on our conversation history and my profile, generate a personalized 3-month action plan (roadmap) for my career orientation as a high school student. Break it down into clear, actionable steps. Return ONLY a JSON array of objects, where each object has 'id' (string), 'title' (string), 'description' (string), and 'status' (must be exactly 'todo'). Do not include any markdown formatting like \`\`\`json.`
    : `Dựa trên lịch sử trò chuyện và hồ sơ của tôi, hãy tạo một kế hoạch hành động (lộ trình) cá nhân hóa trong 3 tháng tới cho việc định hướng nghề nghiệp của tôi (tôi là học sinh THPT). Hãy chia nhỏ thành các bước cụ thể và có thể thực hiện được. CHỈ trả về một mảng JSON chứa các đối tượng, mỗi đối tượng có 'id' (chuỗi), 'title' (chuỗi), 'description' (chuỗi), và 'status' (phải chính xác là 'todo'). Không bao gồm bất kỳ định dạng markdown nào như \`\`\`json.`;

  const activeKey = getGeminiApiKey(userProfile);

  const extractJsonArray = (rawText: string) => {
    let clean = (rawText || '').trim();
    clean = clean.replace(/```json\s*/gi, '').replace(/```\s*/g, '').trim();
    try {
      const parsed = JSON.parse(clean);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    } catch (e) {}
    const s = clean.indexOf('[');
    const e = clean.lastIndexOf(']');
    if (s !== -1 && e !== -1 && e > s) {
      try {
        const parsed = JSON.parse(clean.substring(s, e + 1));
        if (Array.isArray(parsed) && parsed.length > 0) return parsed;
      } catch (err) {}
    }
    return null;
  };

  const callApi = async () => {
    try {
      const response = await fetch('/api/chat', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
              history: chatHistory,
              message: prompt,
              systemInstruction: "You are an expert career counselor. Output ONLY valid JSON array. No other text.",
              apiKey: activeKey
          })
      });

      const contentType = response.headers.get('content-type');
      const isJson = contentType && contentType.includes('application/json');

      if (isJson) {
        const text = await response.text();
        const data = JSON.parse(text);
        if (response.ok && data.text) {
          const parsed = extractJsonArray(data.text);
          if (parsed) return parsed;
        }
      }
    } catch (e: any) {
      console.warn("Backend roadmap proxy attempt failed:", e);
    }

    // Direct Client Fallback Execution if key exists
    try {
      const ai = new GoogleGenAI({ apiKey: activeKey });
      const contents = chatHistory.map(h => ({ role: h.role === 'model' ? 'model' : 'user', parts: [{ text: h.text }] }));
      contents.push({ role: 'user', parts: [{ text: prompt }] });
      const aiResponse = await generateClientContentWithFallback(ai, {
          model: 'gemini-3.6-flash',
          contents,
          config: { systemInstruction: "You are an expert career counselor. Output ONLY valid JSON array. No other text." }
      });
      const parsed = extractJsonArray(aiResponse.text || '');
      if (parsed) return parsed;
    } catch (err) {
      console.warn("Direct client roadmap generation failed, returning resilient fallback:", err);
    }

    throw new Error(isVi ? "Không thể kết nối AI (Kiểm tra API Key)" : "Cannot connect to AI (Check API Key)");
  };

  return await retryWithBackoff(callApi);
};

export const sendChatMessage = async (
  history: { role: string; text: string }[], 
  newMessage: string, 
  language: Language,
  userProfile?: UserProfile | null,
  file?: { data: string; mimeType: string } | null
) => {
  const t = TRANSLATIONS[language];
  let systemInstruction = t.systemInstruction;
  
  if (userProfile?.careerProfile) {
      systemInstruction += `\n\nUser's Career Profile (RIASEC): ${userProfile.careerProfile}`;
  }

  // Check Provider - ONLY use external APIs if user explicitly configured them
  if (userProfile?.aiProvider === AIProvider.N8N && userProfile.customEndpoint) {
      return await sendN8NMessage(userProfile.customEndpoint, history, newMessage, systemInstruction, language, userProfile);
  }

  if (userProfile?.aiProvider === AIProvider.CUSTOM && userProfile.customEndpoint) {
    const endpoint = userProfile.customEndpoint;
    const modelName = userProfile.customModelName || "llama3";
    return await sendExternalApiMessage(endpoint, modelName, history, newMessage, systemInstruction, language);
  }

  // --- DEFAULT: GOOGLE GEMINI ---
  const keysPool = getGeminiApiKeysPool(userProfile);
  const activeKey = getGeminiApiKey(userProfile);

  const callGemini = async () => {
    let lastFetchError: any = null;
    try {
      const response = await fetch('/api/chat', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
              history,
              message: newMessage,
              systemInstruction,
              file,
              apiKey: activeKey || undefined
          })
      });

      const contentType = response.headers.get('content-type');
      const isJson = contentType && contentType.includes('application/json');

      if (isJson) {
          const data = await response.json();
          if (response.ok && data.text) {
            return cleanMarkdownAsterisks(data.text);
          }
          if (data.error) {
            lastFetchError = new Error(data.error);
          }
      } else if (!response.ok) {
          lastFetchError = new Error(`Server returned HTTP ${response.status}`);
      }
    } catch (e: any) {
      lastFetchError = e;
      console.warn("Backend chat proxy fetch error, switching to direct client-side SDK generation:", e);
    }

    // Direct Client GoogleGenAI SDK execution across candidate keys if available
    const candidateKeys = keysPool.length > 0 ? keysPool : (activeKey ? [activeKey] : []);

    let lastClientError: any = null;
    for (const key of candidateKeys) {
      try {
        const ai = new GoogleGenAI({ apiKey: key });
        const contents = history.map(h => ({ role: h.role === 'model' ? 'model' : 'user', parts: [{ text: h.text }] }));
        const userParts: any[] = [{ text: newMessage }];
        if (file) userParts.push({ inlineData: { mimeType: file.mimeType, data: file.data } });
        contents.push({ role: 'user', parts: userParts });
        
        const aiResponse = await generateClientContentWithFallback(ai, {
            model: 'gemini-3.6-flash',
            contents,
            config: { systemInstruction }
        });
        if (aiResponse && aiResponse.text) {
          return cleanMarkdownAsterisks(aiResponse.text);
        }
      } catch (err: any) {
        lastClientError = err;
        console.warn("Client key attempt failed, trying next key:", err);
      }
    }

    if (lastFetchError) {
      throw lastFetchError;
    }
    if (lastClientError) {
      throw lastClientError;
    }

    throw new Error(t.noAiResponse);
  };

  try {
    return await retryWithBackoff(callGemini);
  } catch (error: any) {
    // console.error("Chat API Error:", error);
    throw new Error(cleanFrontEndErrorMessage(error, language));
  }
};

// Function to call a Generic External API (For Custom/Self-Hosted providers only)
const sendExternalApiMessage = async (
  endpoint: string,
  modelName: string,
  history: { role: string; text: string }[],
  newMessage: string,
  systemInstruction: string,
  language: Language
) => {
  const t = TRANSLATIONS[language];
  try {
    const messages = [
      { role: "system", content: systemInstruction },
      ...history.map(h => ({ role: h.role === 'model' ? 'assistant' : 'user', content: h.text })),
      { role: "user", content: newMessage }
    ];

    const response = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: modelName,
        messages: messages,
        stream: false,
        temperature: 0.7
      })
    });

    const text = await response.text();
    let data;
    try {
        data = JSON.parse(text);
    } catch (e) {
        throw new Error(`External API returned invalid JSON (Status: ${response.status})`);
    }

    if (!response.ok) {
        throw new Error(data.error?.message || data.error || `External API Error: ${response.statusText}`);
    }
    
    return data.choices?.[0]?.message?.content || data.message?.content || t.noExternalResponse;
  } catch (error) {
    console.error("External Model Error:", error);
    throw error;
  }
};

// Function to call n8n Webhook
const sendN8NMessage = async (
  webhookUrl: string,
  history: { role: string; text: string }[],
  newMessage: string,
  systemInstruction: string,
  language: Language,
  userProfile?: UserProfile | null
) => {
  const t = TRANSLATIONS[language];
  try {
    const payload = {
        message: newMessage,
        history: history,
        systemInstruction: systemInstruction,
        userEmail: userProfile?.email || 'guest',
        timestamp: new Date().toISOString()
    };

    const response = await fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
    });

    const text = await response.text();
    let data;
    try {
        data = JSON.parse(text);
    } catch (e) {
        throw new Error(`n8n Webhook returned invalid JSON (Status: ${response.status})`);
    }

    if (!response.ok) {
        throw new Error(data.error || `n8n Webhook Error: ${response.statusText}`);
    }
    
    if (data.output && typeof data.output === 'string') return data.output;
    if (data.text && typeof data.text === 'string') return data.text;
    if (data.response && typeof data.response === 'string') return data.response;
    if (data.message && typeof data.message === 'string') return data.message;
    if (data.choices?.[0]?.message?.content) return data.choices[0].message.content;

    return JSON.stringify(data);
  } catch (error) {
    console.error("n8n Error:", error);
    throw error;
  }
};

export class LiveSessionManager {
  language: Language;
  userProfile?: UserProfile | null;
  liveSession: any = null;
  ws: WebSocket | null = null;
  inputContext: AudioContext | null = null;
  outputContext: AudioContext | null = null;
  inputSource: MediaStreamAudioSourceNode | null = null;
  processor: ScriptProcessorNode | null = null;
  analyser: AnalyserNode | null = null;
  outputAnalyser: AnalyserNode | null = null;
  meterAnimFrame: number | null = null;
  stream: MediaStream | null = null;
  speechRecognition: any | null = null;
  speechSynthUtterance: SpeechSynthesisUtterance | null = null;
  isAiSpeaking: boolean = false;
  speechRate: number = 1.0;
  voiceName: string = 'Kore';
  conversationHistory: { role: string; text: string }[] = [];
  activeSources: AudioBufferSourceNode[] = [];
  nextStartTime: number = 0;
  currentAudioElement: HTMLAudioElement | null = null;
  
  onConnect?: () => void;
  onDisconnect?: () => void;
  onError?: (err: any) => void;
  onAudioLevel?: (level: number) => void;
  onTranscript?: (text: string, isUser: boolean) => void;

  isConnected: boolean = false;
  isLiveApiActive: boolean = false;

  constructor(language: Language, userProfile?: UserProfile | null, voiceName: string = 'Kore') { 
    this.language = language;
    this.userProfile = userProfile;
    this.voiceName = voiceName || 'Kore';
    this.liveSession = null;
    this.ws = null;
    this.inputContext = null;
    this.outputContext = null;
    this.inputSource = null;
    this.processor = null;
    this.analyser = null;
    this.outputAnalyser = null;
    this.meterAnimFrame = null;
    this.stream = null;
    this.isConnected = false;
    this.isLiveApiActive = false;
    this.speechRecognition = null;
    this.speechSynthUtterance = null;
    this.isAiSpeaking = false;
    this.speechRate = 1.0;
    this.conversationHistory = [];
    this.activeSources = [];
    this.nextStartTime = 0;
    this.currentAudioElement = null;
  }

  async getAudioInputDevices() {
    try {
        if (!navigator.mediaDevices || !navigator.mediaDevices.enumerateDevices) {
            return [];
        }
        const devices = await navigator.mediaDevices.enumerateDevices();
        return devices.filter(d => d.kind === 'audioinput');
    } catch (e) { return []; }
  }

  async connect(deviceId?: string, decodeAudioDataFn?: any, createBlobFn?: any, decodeFn?: any) {
    const t = TRANSLATIONS[this.language];
    let systemInstruction = this.language === Language.VI
      ? "Bạn là chuyên gia tư vấn hướng nghiệp Career Compass AI. QUY TẮC BẮT BUỘC: 1. Chỉ trả lời 100% bằng tiếng Việt tự nhiên, ấm áp, thân thiện. 2. TUYỆT ĐỐI KHÔNG xuất ra bất kỳ suy nghĩ nội bộ nào, KHÔNG có tiêu đề tiếng Anh ('Confirming...', 'Analyzing...'), KHÔNG pha trộn tiếng Anh. 3. Trả lời ngay tức thì bằng 1-2 câu súc tích (dưới 35 từ), đi thẳng vào trọng tâm hướng nghiệp. 4. Không dùng ký hiệu markdown hay hoa thị (*)."
      : t.voiceSystemInstruction;
    
    if (this.userProfile?.careerProfile) {
        systemInstruction += `\n\nUser's Career Profile (RIASEC): ${this.userProfile.careerProfile}`;
    }

    try {
      if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
        try {
          const constraints = { 
            audio: deviceId 
              ? { deviceId: { exact: deviceId }, echoCancellation: true, noiseSuppression: true, autoGainControl: true } 
              : { echoCancellation: true, noiseSuppression: true, autoGainControl: true } 
          };
          this.stream = await navigator.mediaDevices.getUserMedia(constraints);
        } catch (micErr: any) {
          console.warn("Microphone access notice:", micErr);
          const isVi = this.language === Language.VI;
          const isDenied = micErr?.name === 'NotAllowedError' || micErr?.message?.includes('Permission denied') || micErr?.message?.includes('denied');
          if (isDenied) {
            const msg = isVi 
              ? 'Trình duyệt chưa được cấp quyền Micro. Vui lòng bật quyền truy cập Micro trên thanh địa chỉ trình duyệt.' 
              : 'Microphone permission was denied. Please allow microphone access in your browser.';
            if (this.onError) this.onError(msg);
            this.cleanup();
            if (this.onDisconnect) this.onDisconnect();
            return;
          }
        }
      }

      // 1. Initialize Audio Contexts
      const AudioCtx = window.AudioContext || (window as any).webkitAudioContext;
      this.inputContext = new AudioCtx({ sampleRate: 16000 });
      this.outputContext = new AudioCtx({ sampleRate: 24000 });

      if (this.inputContext.state === 'suspended') {
        await this.inputContext.resume();
      }
      if (this.outputContext.state === 'suspended') {
        await this.outputContext.resume();
      }

      this.startMicLevelMeter();

      // 2. Primary: Direct Client-Side Gemini Live API connection (via @google/genai SDK)
      const apiKey = getGeminiApiKey(this.userProfile);
      let clientConnected = false;

      if (apiKey) {
        try {
          const ai = new GoogleGenAI({ apiKey });
          const liveModels = [
            'gemini-2.5-flash-native-audio-preview-12-2025',
            'gemini-2.5-flash-native-audio-preview-09-2025',
            'gemini-2.5-flash-live-preview',
            'gemini-3.1-flash-live-preview',
            'gemini-2.5-flash'
          ];

          for (const model of liveModels) {
            try {
              console.log(`Attempting client-side Gemini Live connection with model: ${model}`);
              const session = await ai.live.connect({
                model,
                callbacks: {
                  onopen: () => {
                    this.isConnected = true;
                    this.isLiveApiActive = true;
                    this.startPcmAudioStreaming(createBlobFn);
                    if (this.onConnect) this.onConnect();
                  },
                  onmessage: async (message: LiveServerMessage) => {
                    const sc = (message as any).serverContent;
                    if (!sc) return;

                    if (sc.outputAudioTranscription?.text) {
                      const cleanT = cleanVoiceModelOutput(sc.outputAudioTranscription.text, this.language);
                      if (cleanT) this.onTranscript?.(cleanT, false);
                    }
                    if (sc.outputTranscription?.text) {
                      const cleanT = cleanVoiceModelOutput(sc.outputTranscription.text, this.language);
                      if (cleanT) this.onTranscript?.(cleanT, false);
                    }
                    if (sc.inputAudioTranscription?.text) {
                      this.onTranscript?.(sc.inputAudioTranscription.text, true);
                    }
                    if (sc.inputTranscription?.text) {
                      this.onTranscript?.(sc.inputTranscription.text, true);
                    }

                    if (sc.interrupted) {
                      this.stopAllActiveAudio();
                    }

                    if (sc.modelTurn?.parts) {
                      for (const part of sc.modelTurn.parts) {
                        if (part.inlineData?.data) {
                          await this.playPcmAudioChunk(part.inlineData.data, decodeAudioDataFn, decodeFn);
                        }
                        if (part.text) {
                          const cleanPartText = cleanVoiceModelOutput(part.text, this.language);
                          if (cleanPartText) {
                            this.onTranscript?.(cleanPartText, false);
                            this.conversationHistory.push({ role: 'model', text: cleanPartText });
                          }
                        }
                      }
                    }
                  },
                  onclose: () => {
                    console.log("Client-side Gemini Live session closed");
                    if (this.isConnected && this.isLiveApiActive) {
                      this.isLiveApiActive = false;
                      this.startFallbackVoiceInteraction(systemInstruction);
                    }
                  },
                  onerror: (err: any) => {
                    console.warn("Client-side Gemini Live error notice:", err);
                  }
                },
                config: {
                  responseModalities: [Modality.AUDIO],
                  outputAudioTranscription: {},
                  inputAudioTranscription: {},
                  systemInstruction,
                  speechConfig: {
                    voiceConfig: {
                      prebuiltVoiceConfig: { voiceName: this.voiceName || 'Kore' }
                    }
                  }
                }
              });

              this.liveSession = session;
              this.isConnected = true;
              this.isLiveApiActive = true;
              clientConnected = true;
              this.startPcmAudioStreaming(createBlobFn);
              if (this.onConnect) this.onConnect();
              console.log(`Successfully connected directly to Gemini Live API (${model})`);
              break;
            } catch (err: any) {
              console.warn(`Direct model ${model} connection attempt failed:`, err?.message || err);
            }
          }
        } catch (clientLiveErr) {
          console.warn("Client-side Live API init error:", clientLiveErr);
        }
      }

      if (clientConnected) {
        return;
      }

      // 3. Secondary: Try WebSocket Proxy (if custom WS URL or dev server)
      this.connectLiveWebSocket(systemInstruction, decodeAudioDataFn, createBlobFn, decodeFn);

    } catch (e: any) { 
      console.warn("Voice connection init notice:", e);
      this.startFallbackVoiceInteraction(systemInstruction);
    }
  }

  connectLiveWebSocket(systemInstruction: string, decodeAudioDataFn?: any, createBlobFn?: any, decodeFn?: any) {
    try {
      const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
      const customWsUrl = localStorage.getItem('gemini_live_ws_url') || 
                          (import.meta.env as any).VITE_LIVE_WS_URL || 
                          (import.meta.env as any).VITE_WS_URL;
      const wsUrl = customWsUrl || `${protocol}//${window.location.host}/ws`;
      console.log("Connecting to WebSocket URL:", wsUrl);
      const ws = new WebSocket(wsUrl);
      this.ws = ws;

      const activeKey = getGeminiApiKey(this.userProfile);

      ws.onopen = () => {
        console.log("Connected to Gemini Live WebSocket proxy");
        // Send initial configuration to start Gemini Live with live model
        ws.send(JSON.stringify({
          type: "config",
          systemInstruction,
          voiceName: this.voiceName || 'Kore',
          apiKey: activeKey || undefined
        }));

        this.isConnected = true;
        if (this.onConnect) this.onConnect();

        // Start streaming mic audio to Live API
        this.startPcmAudioStreaming(createBlobFn);
      };

      ws.onmessage = async (event) => {
        try {
          const msg = JSON.parse(event.data);

          if (msg.error || msg.type === "fallback") {
            console.log("Live API fallback notice, starting assistant voice mode:", msg.error || msg.message);
            this.isLiveApiActive = false;
            this.startFallbackVoiceInteraction(systemInstruction);
            return;
          }

          if (msg.type === "connected") {
            this.isLiveApiActive = true;
            return;
          }

          // Handle interruption (User spoke while AI was speaking)
          if (msg.serverContent?.interrupted || msg.interrupted) {
            this.stopAllActiveAudio();
            return;
          }

          // Handle server content and audio parts
          if (msg.serverContent?.modelTurn?.parts) {
            let hasInlineAudio = false;
            for (const part of msg.serverContent.modelTurn.parts) {
              if (part.inlineData?.data) {
                hasInlineAudio = true;
                // Play raw 24kHz PCM audio from Gemini Live
                await this.playPcmAudioChunk(part.inlineData.data, decodeAudioDataFn, decodeFn);
              }
              if (part.text) {
                if (this.onTranscript) this.onTranscript(part.text, false);
                this.conversationHistory.push({ role: 'model', text: part.text });
                if (!hasInlineAudio) {
                  await this.speakAi(part.text);
                }
              }
            }
          }

          // Handle live speech transcriptions
          if (msg.serverContent?.outputAudioTranscription?.text) {
            if (this.onTranscript) this.onTranscript(msg.serverContent.outputAudioTranscription.text, false);
          }
          if (msg.serverContent?.inputAudioTranscription?.text) {
            if (this.onTranscript) this.onTranscript(msg.serverContent.inputAudioTranscription.text, true);
          }

        } catch (err) {
          console.warn("WS message parse error:", err);
        }
      };

      ws.onerror = (err) => {
        console.warn("WebSocket Live API error:", err);
        if (!this.isLiveApiActive) {
          this.startFallbackVoiceInteraction(systemInstruction);
        }
      };

      ws.onclose = () => {
        console.log("WebSocket Live API closed");
        if (this.isConnected && this.isLiveApiActive) {
          this.isLiveApiActive = false;
          this.startFallbackVoiceInteraction(systemInstruction);
        }
      };

    } catch (wsErr) {
      console.warn("WebSocket init error, using fallback:", wsErr);
      this.startFallbackVoiceInteraction(systemInstruction);
    }
  }

  startPcmAudioStreaming(createBlobFn?: any) {
    if (!this.inputContext || !this.stream) return;

    try {
      if (!this.inputSource) {
        this.inputSource = this.inputContext.createMediaStreamSource(this.stream);
      }

      // ScriptProcessorNode buffers audio samples at 16kHz
      const bufferSize = 2048;
      const processor = this.inputContext.createScriptProcessor(bufferSize, 1, 1);
      this.processor = processor;

      processor.onaudioprocess = (e) => {
        if (!this.isConnected) return;

        const inputData = e.inputBuffer.getChannelData(0);
        
        let pcmBase64 = '';
        if (createBlobFn) {
          const blob = createBlobFn(inputData, 16000);
          pcmBase64 = blob.data;
        } else {
          // Convert Float32Array to 16-bit PCM little endian Base64
          const pcm16 = new Int16Array(inputData.length);
          for (let i = 0; i < inputData.length; i++) {
            const s = Math.max(-1, Math.min(1, inputData[i]));
            pcm16[i] = s < 0 ? s * 0x8000 : s * 0x7FFF;
          }
          const uint8 = new Uint8Array(pcm16.buffer);
          let binary = '';
          for (let i = 0; i < uint8.byteLength; i++) {
            binary += String.fromCharCode(uint8[i]);
          }
          pcmBase64 = btoa(binary);
        }

        if (pcmBase64) {
          if (this.liveSession) {
            try {
              this.liveSession.sendRealtimeInput({
                audio: {
                  data: pcmBase64,
                  mimeType: "audio/pcm;rate=16000"
                }
              });
            } catch (liveErr) {
              try {
                (this.liveSession as any).sendRealtimeInput({
                  media: {
                    data: pcmBase64,
                    mimeType: "audio/pcm;rate=16000"
                  }
                });
              } catch (e) {}
            }
          } else if (this.ws && this.ws.readyState === WebSocket.OPEN) {
            this.ws.send(JSON.stringify({
              realtimeInput: [{
                data: pcmBase64,
                mimeType: "audio/pcm;rate=16000"
              }]
            }));
          }
        }
      };

      this.inputSource.connect(processor);
      processor.connect(this.inputContext.destination);

    } catch (e) {
      console.warn("PCM audio streaming setup notice:", e);
    }
  }

  async playPcmAudioChunk(base64Data: string, decodeAudioDataFn?: any, decodeFn?: any) {
    if (!this.outputContext) return;

    try {
      if (this.outputContext.state === 'suspended') {
        await this.outputContext.resume();
      }

      let audioBuffer: AudioBuffer;

      if (decodeAudioDataFn && decodeFn) {
        const rawBytes = decodeFn(base64Data);
        audioBuffer = await decodeAudioDataFn(rawBytes, this.outputContext, 24000, 1);
      } else {
        // Fallback PCM decode
        const binaryStr = atob(base64Data);
        const bytes = new Uint8Array(binaryStr.length);
        for (let i = 0; i < binaryStr.length; i++) {
          bytes[i] = binaryStr.charCodeAt(i);
        }
        const dataInt16 = new Int16Array(bytes.buffer);
        audioBuffer = this.outputContext.createBuffer(1, dataInt16.length, 24000);
        const channelData = audioBuffer.getChannelData(0);
        for (let i = 0; i < dataInt16.length; i++) {
          channelData[i] = dataInt16[i] / 32768.0;
        }
      }

      const source = this.outputContext.createBufferSource();
      source.buffer = audioBuffer;
      source.connect(this.outputContext.destination);

      const currentTime = this.outputContext.currentTime;
      const startTime = Math.max(currentTime, this.nextStartTime);
      source.start(startTime);
      this.nextStartTime = startTime + audioBuffer.duration;

      this.activeSources.push(source);
      this.isAiSpeaking = true;

      source.onended = () => {
        const idx = this.activeSources.indexOf(source);
        if (idx !== -1) this.activeSources.splice(idx, 1);
        if (this.activeSources.length === 0) {
          this.isAiSpeaking = false;
        }
      };

    } catch (e) {
      console.warn("PCM Playback notice:", e);
    }
  }

  stopAllActiveAudio() {
    for (const src of this.activeSources) {
      try { src.stop(); } catch (e) {}
    }
    this.activeSources = [];
    this.nextStartTime = 0;
    this.isAiSpeaking = false;
  }

  startMicLevelMeter() {
    if (!this.inputContext || !this.stream) return;
    try {
      if (!this.inputSource) {
        this.inputSource = this.inputContext.createMediaStreamSource(this.stream);
      }
      this.analyser = this.inputContext.createAnalyser();
      this.analyser.fftSize = 256;
      this.inputSource.connect(this.analyser);

      const bufferLength = this.analyser.frequencyBinCount;
      const dataArray = new Uint8Array(bufferLength);

      const updateMeter = () => {
        if (!this.isConnected || !this.analyser) return;

        this.analyser.getByteFrequencyData(dataArray);
        let sum = 0;
        for (let i = 0; i < bufferLength; i++) {
          sum += dataArray[i];
        }
        const avg = (sum / bufferLength) / 255;
        
        if (this.onAudioLevel) {
          if (this.isAiSpeaking) {
            this.onAudioLevel(0.3 + Math.random() * 0.45);
          } else {
            this.onAudioLevel(avg);
          }
        }

        this.meterAnimFrame = requestAnimationFrame(updateMeter);
      };

      updateMeter();
    } catch (e) {
      console.warn("AnalyserNode setup notice:", e);
    }
  }

  async sendTextMessage(userText: string) {
    if (!userText || !userText.trim()) return;
    const cleanText = userText.trim();

    if (this.onTranscript) this.onTranscript(cleanText, true);
    this.conversationHistory.push({ role: 'user', text: cleanText });

    // If direct client-side Gemini Live session is connected
    if (this.isLiveApiActive && this.liveSession) {
      try {
        this.liveSession.sendRealtimeInput({ text: cleanText });
        return;
      } catch (e) {
        try {
          this.liveSession.send({
            clientContent: {
              turns: [{ role: 'user', parts: [{ text: cleanText }] }],
              turnComplete: true
            }
          });
          return;
        } catch (e2) {}
      }
    }

    // If Gemini Live is connected via WebSocket proxy, send realtime text directly
    if (this.isLiveApiActive && this.ws && this.ws.readyState === WebSocket.OPEN) {
      this.ws.send(JSON.stringify({ text: cleanText }));
      return;
    }

    // Otherwise use ultra-fast voice fallback
    const t = TRANSLATIONS[this.language];
    const systemInstruction = this.language === Language.VI
      ? "Bạn là chuyên gia tư vấn hướng nghiệp Career Compass AI. QUY TẮC BẮT BUỘC: 1. Chỉ trả lời 100% bằng tiếng Việt tự nhiên, ấm áp, thân thiện. 2. TUYỆT ĐỐI KHÔNG xuất ra bất kỳ suy nghĩ nội bộ nào, KHÔNG có tiêu đề tiếng Anh ('Confirming...', 'Analyzing...'), KHÔNG pha trộn tiếng Anh. 3. Trả lời ngay tức thì bằng 1-2 câu súc tích (dưới 35 từ), đi thẳng vào trọng tâm hướng nghiệp. 4. Không dùng ký hiệu markdown hay hoa thị (*)."
      : t.voiceSystemInstruction;

    try {
      this.isAiSpeaking = true;
      const aiText = await requestVoiceAiFastResponse(cleanText, systemInstruction, this.language, this.userProfile);

      if (aiText && aiText !== "{}" && !aiText.startsWith("{")) {
        if (this.onTranscript) this.onTranscript(aiText, false);
        this.conversationHistory.push({ role: 'model', text: aiText });
        await this.speakAi(aiText);
      } else {
        const fallback = this.language === Language.VI 
          ? "Tôi đã ghi nhận ý kiến của bạn. Bạn muốn tư vấn thêm về lộ trình hay ngành nghề nào?"
          : "I have noted your question. Which career path or roadmap would you like to explore further?";
        if (this.onTranscript) this.onTranscript(fallback, false);
        this.conversationHistory.push({ role: 'model', text: fallback });
        await this.speakAi(fallback);
      }
    } catch (err: any) {
      console.error("Voice text response error:", err);
      this.isAiSpeaking = false;
      const errMsg = cleanFrontEndErrorMessage(err, this.language);
      if (this.onTranscript) this.onTranscript(errMsg, false);
      this.conversationHistory.push({ role: 'model', text: errMsg });
      await this.speakAi(errMsg);
    }
  }

  async startFallbackVoiceInteraction(systemInstruction: string) {
    this.isConnected = true;
    this.isLiveApiActive = false;
    if (this.onConnect) this.onConnect();

    // Initial welcome greeting
    const welcomeText = this.language === Language.VI
      ? "Xin chào! Tôi là Cố vấn Hướng nghiệp AI. Bạn đang quan tâm hay cần tư vấn về ngành nghề nào?"
      : "Hello! I am your AI Career Counselor. What career field or direction are you interested in today?";
    
    if (this.onTranscript) this.onTranscript(welcomeText, false);
    this.conversationHistory.push({ role: 'model', text: welcomeText });
    await this.speakAi(welcomeText);

    const SpeechRec = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRec) {
      console.warn("SpeechRecognition not supported in this browser");
      return;
    }

    try {
      if (this.speechRecognition) {
        try { this.speechRecognition.stop(); } catch (e) {}
      }

      const recognition = new SpeechRec();
      recognition.continuous = true;
      recognition.interimResults = true;
      recognition.maxAlternatives = 1;
      recognition.lang = this.language === Language.VI ? 'vi-VN' : 'en-US';

      let isProcessingVoice = false;
      let lastProcessedSpeech = '';
      let pendingSpeech = '';
      let silenceTimer: any = null;

      const triggerVoiceResponse = async (speechToProcess: string) => {
        if (!speechToProcess || speechToProcess.length < 2 || isProcessingVoice) return;
        if (speechToProcess === lastProcessedSpeech) return;

        lastProcessedSpeech = speechToProcess;
        isProcessingVoice = true;

        if (this.onTranscript) this.onTranscript(speechToProcess, true);
        this.conversationHistory.push({ role: 'user', text: speechToProcess });
        
        try {
          this.isAiSpeaking = true;
          const aiText = await requestVoiceAiFastResponse(speechToProcess, systemInstruction, this.language, this.userProfile);
          
          if (aiText && aiText !== "{}" && !aiText.startsWith("{")) {
            if (this.onTranscript) this.onTranscript(aiText, false);
            this.conversationHistory.push({ role: 'model', text: aiText });
            await this.speakAi(aiText);
          } else {
            const fallback = this.language === Language.VI 
              ? "Tôi đã nghe rõ câu hỏi của bạn. Bạn muốn định hướng về kỹ năng hay cơ hội việc làm của ngành này?"
              : "I heard your question clearly. Would you like advice on skills or job opportunities in this field?";
            if (this.onTranscript) this.onTranscript(fallback, false);
            this.conversationHistory.push({ role: 'model', text: fallback });
            await this.speakAi(fallback);
          }
        } catch (err: any) {
          console.error("Voice AI counseling error:", err);
          this.isAiSpeaking = false;
          const errMsg = cleanFrontEndErrorMessage(err, this.language);
          if (this.onTranscript) this.onTranscript(errMsg, false);
          this.conversationHistory.push({ role: 'model', text: errMsg });
          await this.speakAi(errMsg);
        } finally {
          isProcessingVoice = false;
          pendingSpeech = '';
          setTimeout(() => {
            if (lastProcessedSpeech === speechToProcess) {
              lastProcessedSpeech = '';
            }
          }, 2500);
        }
      };

      recognition.onresult = (event: any) => {
        // Natural interruption: If user starts speaking while AI audio is playing, stop audio immediately
        if (this.isAiSpeaking || (window.speechSynthesis && window.speechSynthesis.speaking)) {
          this.stopAllActiveAudio();
          this.isAiSpeaking = false;
        }

        let interimTranscript = '';
        let finalTranscript = '';

        for (let i = event.resultIndex; i < event.results.length; i++) {
          const transcript = event.results[i][0]?.transcript || '';
          if (event.results[i].isFinal) {
            finalTranscript += transcript;
          } else {
            interimTranscript += transcript;
          }
        }

        const currentSpeech = (finalTranscript || interimTranscript).trim();
        if (currentSpeech) {
          pendingSpeech = currentSpeech;
          // Live real-time transcript update to UI
          if (this.onTranscript) this.onTranscript(currentSpeech, true);

          // Fast low-latency silence debounce (550ms)
          if (silenceTimer) clearTimeout(silenceTimer);
          silenceTimer = setTimeout(() => {
            if (pendingSpeech && !isProcessingVoice) {
              triggerVoiceResponse(pendingSpeech);
            }
          }, 550);
        }
      };

      const restartSpeechRecognition = () => {
        if (this.isConnected && !this.isLiveApiActive && this.speechRecognition === recognition) {
          setTimeout(() => {
            try {
              recognition.start();
            } catch (e) {
              // Ignore if already active
            }
          }, 250);
        }
      };

      recognition.onerror = (err: any) => {
        if (err?.error !== 'no-speech' && err?.error !== 'aborted') {
          console.warn("Speech recognition error notice:", err?.error || err);
        }
        restartSpeechRecognition();
      };

      recognition.onend = () => {
        if (pendingSpeech && !isProcessingVoice) {
          triggerVoiceResponse(pendingSpeech);
        }
        restartSpeechRecognition();
      };

      try {
        recognition.start();
      } catch (e) {}
      this.speechRecognition = recognition;

    } catch (e: any) {
      console.warn("Speech recognition setup notice:", e);
    }
  }

  async playBase64Audio(base64Data: string, mimeType: string = 'audio/wav') {
    try {
      this.stopCurrentAudio();
      const audioUrl = `data:${mimeType};base64,${base64Data}`;
      const audio = new Audio(audioUrl);
      this.currentAudioElement = audio;
      this.isAiSpeaking = true;

      audio.onended = () => {
        this.isAiSpeaking = false;
        this.currentAudioElement = null;
      };
      audio.onerror = () => {
        this.isAiSpeaking = false;
        this.currentAudioElement = null;
      };

      await audio.play();
    } catch (playErr) {
      console.warn("Audio playback error:", playErr);
      this.isAiSpeaking = false;
    }
  }

  async speakAi(text: string) {
    if (!text || !text.trim()) return;
    const cleanText = cleanVoiceModelOutput(text, this.language);
    if (!cleanText) return;

    // 1. Try High-Quality Server Gemini Native Audio TTS
    try {
      const activeKey = getGeminiApiKey(this.userProfile);
      const res = await fetch('/api/tts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          text: cleanText,
          voiceName: this.voiceName || 'Kore',
          language: this.language === Language.VI ? 'vi' : 'en',
          apiKey: activeKey || undefined
        })
      });

      if (res.ok) {
        const data = await res.json();
        if (data.audioData) {
          await this.playBase64Audio(data.audioData, data.mimeType || 'audio/wav');
          return;
        }
      }
    } catch (ttsErr) {
      console.warn("Server TTS attempt notice, switching to browser TTS:", ttsErr);
    }

    // 2. High-Quality Browser Speech Synthesis Fallback (Rate = 1.0, Priority on Natural/Google Voices)
    this.speakBrowserAi(cleanText);
  }

  speakBrowserAi(text: string) {
    if (!('speechSynthesis' in window)) {
      this.isAiSpeaking = false;
      return;
    }
    try {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.lang = this.language === Language.VI ? 'vi-VN' : 'en-US';
      utterance.rate = this.speechRate || 1.0;
      utterance.pitch = 1.0;

      const voices = window.speechSynthesis.getVoices();
      if (this.language === Language.VI) {
        // Prioritize natural Vietnamese voices
        const viVoice = voices.find(v => 
          v.name.toLowerCase().includes("google") && (v.lang.startsWith("vi") || v.lang.includes("vi-VN"))
        ) || voices.find(v => 
          (v.name.toLowerCase().includes("hoaimy") || v.name.toLowerCase().includes("namminh") || v.name.toLowerCase().includes("natural") || v.name.toLowerCase().includes("linh") || v.name.toLowerCase().includes("an")) &&
          (v.lang.startsWith("vi") || v.lang.includes("vi-VN"))
        ) || voices.find(v => v.lang.startsWith("vi") || v.lang.includes("vi-VN"));

        if (viVoice) utterance.voice = viVoice;
      } else {
        const enVoice = voices.find(v => 
          (v.name.toLowerCase().includes("google") || v.name.toLowerCase().includes("natural") || v.name.toLowerCase().includes("samantha")) &&
          (v.lang.startsWith("en-US") || v.lang.startsWith("en-GB"))
        ) || voices.find(v => v.lang.startsWith("en-US") || v.lang.startsWith("en-GB"));

        if (enVoice) utterance.voice = enVoice;
      }

      this.isAiSpeaking = true;

      const finishSpeaking = () => {
        this.isAiSpeaking = false;
        this.speechSynthUtterance = null;
        (window as any)._activeUtterance = null;
      };

      utterance.onend = finishSpeaking;
      utterance.onerror = finishSpeaking;

      this.speechSynthUtterance = utterance;
      (window as any)._activeUtterance = utterance; // Prevent garbage-collection cutoff in Chromium

      window.speechSynthesis.speak(utterance);

      // Chrome safety watchdog
      const maxDuration = Math.max(4000, (text.length / 10) * 1000);
      setTimeout(() => {
        if (this.isAiSpeaking && !window.speechSynthesis.speaking) {
          this.isAiSpeaking = false;
        }
      }, maxDuration);
    } catch (e) {
      this.isAiSpeaking = false;
    }
  }

  stopCurrentAudio() {
    this.stopAllActiveAudio();
    if (this.currentAudioElement) {
      try {
        this.currentAudioElement.pause();
        this.currentAudioElement.currentTime = 0;
      } catch (e) {}
      this.currentAudioElement = null;
    }
    if ('speechSynthesis' in window) {
      try { window.speechSynthesis.cancel(); } catch (e) {}
    }
    this.isAiSpeaking = false;
  }

  disconnect() { 
    if (this.liveSession) {
      try { this.liveSession.close(); } catch (e) {}
      this.liveSession = null;
    }
    if (this.ws) {
      try { this.ws.close(); } catch (e) {}
      this.ws = null;
    }
    if (this.speechRecognition) {
      try { this.speechRecognition.stop(); } catch (e) {}
      this.speechRecognition = null;
    }
    if ('speechSynthesis' in window) {
      try { window.speechSynthesis.cancel(); } catch (e) {}
    }
    this.cleanup(); 
  }

  cleanup() {
    if (this.meterAnimFrame !== null) {
      cancelAnimationFrame(this.meterAnimFrame);
      this.meterAnimFrame = null;
    }
    this.stopAllActiveAudio();
    this.isAiSpeaking = false;
    if (this.liveSession) {
      try { this.liveSession.close(); } catch (e) {}
      this.liveSession = null;
    }
    this.processor?.disconnect();
    this.analyser?.disconnect();
    this.outputAnalyser?.disconnect();
    this.inputSource?.disconnect();
    this.stream?.getTracks().forEach(t => t.stop());
    this.inputContext?.close();
    this.outputContext?.close();
    this.inputContext = null;
    this.outputContext = null;
    this.processor = null;
    this.stream = null;
    this.analyser = null;
    this.outputAnalyser = null;
    this.isConnected = false;
    this.isLiveApiActive = false;
  }
}

export const generateChatTitle = async (message: string, language: Language) => {
  if (!message || !message.trim()) return '';
  const firstMsg = message.trim();
  const lowerMsg = firstMsg.toLowerCase();
  
  // Instant clean title for common short greetings
  if (['xin chào', 'chào bạn', 'chào', 'hello', 'hi', 'hey', 'alo', 'chao ban', 'chao'].includes(lowerMsg)) {
    return language === Language.VI ? 'Bắt đầu cuộc trò chuyện' : 'General Inquiry';
  }

  const customKey = getGeminiApiKey();

  const sanitizeTitle = (raw: string): string => {
    const t = cleanMarkdownAsterisks(raw || '').replace(/^["']|["']$/g, '').replace(/\n.*$/s, '').trim();
    if (!t || t.length > 35 || t.includes('Chào bạn') || t.includes('Đối với') || t.includes('hành trình') || t.includes('Generate title') || t.includes('Language required')) {
      return firstMsg.length > 25 ? firstMsg.slice(0, 25) + '...' : firstMsg;
    }
    return t;
  };

  const callApi = async () => {
    const response = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            history: [],
            message: `Generate a short concise 2-4 word title in ${language === Language.EN ? 'English' : 'Vietnamese'} for this inquiry: "${firstMsg.slice(0, 50)}". Return ONLY 2-4 words, no quotes, no extra text.`,
            systemInstruction: "You are a concise title generator. Return only 2 to 4 words. No greeting, no punctuation.",
            apiKey: customKey || undefined
        })
    });
    
    const contentType = response.headers.get('content-type');
    const isJson = contentType && contentType.includes('application/json');
    if (!isJson) {
        if (customKey) {
            const ai = new GoogleGenAI({ apiKey: customKey });
            const aiResponse = await generateClientContentWithFallback(ai, {
                model: 'gemini-3.6-flash',
                contents: [{ role: 'user', parts: [{ text: `Generate a 2-4 word title: "${firstMsg.slice(0, 50)}"` }] }],
                config: { systemInstruction: "Return only 2 to 4 words" }
            });
            return sanitizeTitle(aiResponse.text || '');
        }
        return firstMsg.length > 25 ? firstMsg.slice(0, 25) + '...' : firstMsg;
    }

    const textResponse = await response.text();
    let data;
    try { data = JSON.parse(textResponse); } catch(e) { throw new Error('Invalid JSON'); }
    if (data.error) throw new Error(data.error);
    return sanitizeTitle(data.text || '');
  };

  try {
    return await retryWithBackoff(callApi);
  } catch (error) {
    return firstMsg.length > 25 ? firstMsg.slice(0, 25) + '...' : firstMsg;
  }
};

export const searchUniversityScores = async (query: string, language: Language) => {
  const isVi = language === Language.VI;
  const systemInstruction = isVi
    ? "Bạn là một chuyên gia tư vấn tuyển sinh đại học hàng đầu Việt Nam. Hãy sử dụng tính năng Google Search đi kèm để tìm kiếm ĐIỂM CHUẨN (điểm chuẩn học bạ, điểm chuẩn thi tốt nghiệp THPT, hoặc điểm chuẩn ĐGNL) mới nhất và chính xác nhất phù hợp với yêu cầu. Luôn ưu tiên thông tin chính thống từ các nguồn uy tín như Báo VnExpress (https://vnexpress.net/giao-duc/tuyen-sinh), Báo Tuổi Trẻ (https://tuoitre.vn/giao-duc.htm), Báo Thanh Niên (https://thanhnien.vn/giao-duc.html), Cổng Bộ GD&ĐT (https://thisinh.thitotnghiepthpt.edu.vn) hoặc Cổng thông tin tuyển sinh chính thức của trường Đại học. Trình bày thông tin rõ ràng dưới dạng bảng Markdown (gồm các cột: Trường, Ngành/Mã ngành, Tổ hợp xét tuyển, Điểm chuẩn, Năm áp dụng) và đưa ra lời khuyên hữu ích cho học sinh. QUAN TRỌNG: Ở phần nguồn tham khảo, hãy luôn gắn link Markdown có thể bấm được (ví dụ: [VnExpress Tuyển sinh](https://vnexpress.net/giao-duc/tuyen-sinh), [Cổng tuyển sinh](https://...)) thay vì chỉ để chữ văn bản thuần."
    : "You are an elite university admission advisor in Vietnam. Use the Google Search tool to find the absolute latest and most accurate admission scores matching the university or major requested. Prioritize official and prestigious Vietnamese sources like VnExpress, Tuoi Tre, Thanh Nien, or official university portals. Present results in a neat Markdown table containing: University, Major/Code, Exam Group, Score, and Year. Provide strategic advice below. IMPORTANT: In the sources section, always provide clickable Markdown links (e.g. [Official Portal](https://...)) instead of plain text names.";
  
  const customKey = getGeminiApiKey();

  const callApi = async () => {
    const promptMessage = isVi
      ? `Tra cứu điểm chuẩn đại học mới nhất của trường/ngành: "${query}". Chú ý: Hiện tại đang là năm 2026. Hãy tìm kiếm các dữ liệu mới nhất có sẵn (ví dụ điểm chuẩn năm 2025, 2024). Luôn cung cấp liên kết URL web và tên nguồn báo hoặc trang tuyển sinh chính thống mà bạn lấy dữ liệu dạng liên kết [Tên nguồn](URL).`
      : `Find the latest university admission scores for: "${query}". Note: The current year is 2026, so look for the most recent data (e.g., 2025, 2024 figures) using actual search grounding and specify the sources with clickable Markdown links [Source Name](URL).`;

    try {
      const response = await fetch('/api/search', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
              history: [],
              message: promptMessage,
              systemInstruction,
              apiKey: customKey || undefined
          })
      });
      
      const contentType = response.headers.get('content-type');
      const isJson = contentType && contentType.includes('application/json');
      if (isJson) {
        const textResponse = await response.text();
        const data = JSON.parse(textResponse);
        if (response.ok && data?.text) {
          return {
            text: cleanMarkdownAsterisks(data.text),
            groundingMetadata: data.groundingMetadata || null
          };
        }
      }
    } catch (err) {
      // console.warn("Backend search proxy failed:", err);
    }

    if (customKey) {
      try {
        const ai = new GoogleGenAI({ apiKey: customKey });
        const aiResponse = await generateClientContentWithFallback(ai, {
            model: 'gemini-3.6-flash',
            contents: [{ role: 'user', parts: [{ text: promptMessage }] }],
            config: { 
                systemInstruction,
                tools: [{ googleSearch: {} }]
            }
        });
        return {
            text: cleanMarkdownAsterisks(aiResponse.text || TRANSLATIONS[language].noAiResponse),
            groundingMetadata: aiResponse.candidates?.[0]?.groundingMetadata || null
        };
      } catch (clientErr) {
        // Fall through to synthesis fallback
      }
    }

    throw new Error(isVi ? "Không thể kết nối AI (Kiểm tra API Key)" : "Cannot connect to AI (Check API Key)");
  };

  return await retryWithBackoff(callApi);
};

export const compareCareers = async (career1: string, career2: string, language: Language) => {
  const systemInstruction = `You are an expert senior career analyst and strategist. Return ONLY a valid JSON object comparing two given careers in depth.
The JSON structure must be EXACTLY:
{
  "career1": {
    "name": "Career 1 Name",
    "description": "Short overview description without markdown asterisks",
    "salary": "Salary range or specific average details (e.g. 20 - 55 triệu VNĐ/tháng)",
    "demand": "Market demand details with growth rates",
    "competition": "Competition description and entry barriers",
    "workLife": "Work-life balance and stress level details",
    "skills": ["Skill 1", "Skill 2", "Skill 3"],
    "careerPath": "Advancement path or stages (e.g. Junior -> Senior -> Lead)",
    "aiRisk": "AI disruption threat level and reason",
    "education": "Required education, bootcamps or key certifications",
    "suitability": "Traits or interests of people who would excel here"
  },
  "career2": {
    "name": "Career 2 Name",
    "description": "Short overview description without markdown asterisks",
    "salary": "Salary range or specific average details (e.g. 25 - 65 triệu VNĐ/tháng)",
    "demand": "Market demand details with growth rates",
    "competition": "Competition description and entry barriers",
    "workLife": "Work-life balance and stress level details",
    "skills": ["Skill 1", "Skill 2", "Skill 3"],
    "careerPath": "Advancement path or stages (e.g. Junior -> Senior -> Lead)",
    "aiRisk": "AI disruption threat level and reason",
    "education": "Required education, bootcamps or key certifications",
    "suitability": "Traits or interests of people who would excel here"
  },
  "comparisonPoints": {
    "salaryWinner": "career1" | "career2" | "tie",
    "demandWinner": "career1" | "career2" | "tie",
    "workLifeWinner": "career1" | "career2" | "tie",
    "aiResilienceWinner": "career1" | "career2" | "tie",
    "summaryAnalysis": "A deep analysis of the trade-offs and differences between the two careers.",
    "recommendation": "Actionable career advice on how to choose between them depending on personal traits."
  }
}
Do NOT include any markdown formatting like \`\`\`json. Ensure all strings are translated into the requested language (either Vietnamese or English). Do not use asterisks (*) in text values.`;
  
  const customKey = getGeminiApiKey();

  const callApi = async () => {
    const prompt = `Provide an in-depth comparison between "${career1}" and "${career2}". Language requested: ${language === Language.EN ? 'English' : 'Vietnamese'}. Make the analysis highly specific, detailed, and realistic (include local Vietnamese salary ranges in VNĐ/tháng). Clean all asterisks from output.`;
    
    try {
      const response = await fetch('/api/chat', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
              history: [], message: prompt, systemInstruction, apiKey: customKey || undefined
          })
      });
      
      const contentType = response.headers.get('content-type');
      const isJson = contentType && contentType.includes('application/json');
      
      if (isJson) {
        const textResponse = await response.text();
        const data = JSON.parse(textResponse);
        if (response.ok && data?.text) {
          let jsonStr = (data.text || '').trim();
          const firstBrace = jsonStr.indexOf('{');
          const lastBrace = jsonStr.lastIndexOf('}');
          if (firstBrace !== -1 && lastBrace > firstBrace) {
            jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);
            try {
              const parsed = JSON.parse(jsonStr);
              if (parsed.career1 && parsed.career2) {
                return cleanMarkdownAsterisks(parsed);
              }
            } catch (e) {}
          }
        }
      }
    } catch (err) {
      console.warn("Backend compare proxy call failed:", err);
    }

    // Direct client fallback if custom key exists
    try {
      const ai = new GoogleGenAI({ apiKey: customKey });
      const aiResponse = await generateClientContentWithFallback(ai, {
          model: 'gemini-3.6-flash',
          contents: [{ role: 'user', parts: [{ text: prompt }] }],
          config: { systemInstruction }
      });
      let jsonStr = (aiResponse.text || '').trim();
      const firstBrace = jsonStr.indexOf('{');
      const lastBrace = jsonStr.lastIndexOf('}');
      if (firstBrace !== -1 && lastBrace > firstBrace) {
        jsonStr = jsonStr.substring(firstBrace, lastBrace + 1);
        const parsed = JSON.parse(jsonStr);
        if (parsed.career1 && parsed.career2) {
          return cleanMarkdownAsterisks(parsed);
        }
      }
    } catch (clientErr) {
      console.warn("Client fallback comparison failed:", clientErr);
    }

    throw new Error(language === Language.VI ? "Không thể kết nối AI (Kiểm tra API Key)" : "Cannot connect to AI (Check API Key)");
  };

  return await retryWithBackoff(callApi);
};

export const searchScholarships = async (
  query: string,
  language: Language,
  userProfile?: UserProfile | null
) => {
  const profileDetails = userProfile 
    ? `\n\nUser Profile:\nName: ${userProfile.name}\nGoal: ${userProfile.careerGoal || 'Exploring'}\nProfile (RIASEC): ${userProfile.careerProfile ? userProfile.careerProfile : 'Not taken'}`
    : '';

  const isVi = language === Language.VI;
  const systemInstruction = isVi
    ? `Bạn là chuyên gia cố vấn săn học bổng và hỗ trợ tài chính du học hàng đầu. Hãy tìm kiếm danh sách 3 - 5 chương trình học bổng thực tế, còn hạn hoặc mở định kỳ tương ứng với từ khóa tìm kiếm: "${query}".
Với mỗi học bổng, trình bày chi tiết theo định dạng:
### 🎓 [Tên học bổng đầy đủ]
- **Đơn vị / Tổ chức cấp**: Tên quỹ tài trợ / Trường đại học / Chính phủ
- **Giá trị tài trợ**: Số tiền hoặc % học phí cụ thể (Toàn phần, 50-100% học phí, sinh hoạt phí)
- **Đối tượng & Điều kiện xét tuyển**: Điểm GPA yêu cầu, chứng chỉ tiếng Anh (IELTS/TOEFL), bài luận hoặc kinh nghiệm
- **Hạn nộp hồ sơ & Kỳ nhập học**: Mốc thời gian tuyển sinh cụ thể
- **Hướng dẫn ứng tuyển & Link/Cổng thông tin**: Nơi tiếp nhận hồ sơ dạng Link Markdown có thể bấm được: [Tên cổng thông tin / Link nộp hồ sơ](https://...)

QUAN TRỌNG: Hãy luôn gắn link Markdown có thể bấm trực tiếp cho các cổng thông tin, trang học bổng chính thức hoặc website trường/đại sứ quán.`
    : `You are a premier scholarship and study abroad advisor. Search for 3 - 5 real, active or recurring scholarship programs matching the search query: "${query}".
For each scholarship, provide:
### 🎓 [Full Scholarship Name]
- **Sponsoring Body / University**: Sponsoring Foundation / Government / University
- **Funding Value**: Exact grant amounts or tuition coverage (Full tuition, stipend, flight)
- **Eligibility & Requirements**: Minimum GPA, English certificates (IELTS/TOEFL), essays, achievements
- **Application Deadline & Intakes**: Specific timeline and deadlines
- **Application Process & Portal**: Official portal guidance with clickable Markdown link [Official Portal / Application Link](https://...)

IMPORTANT: Always include clickable Markdown links for official application portals.`;

  const customKey = getGeminiApiKey(userProfile);

  const callApi = async () => {
    const promptMessage = isVi
      ? `Tìm kiếm các chương trình học bổng, quỹ tài trợ du học hoặc học bổng đại học cho từ khóa: "${query}"${profileDetails}. Yêu cầu cung cấp thông tin chi tiết, chính xác kèm đường link Markdown có thể bấm được.`
      : `Search for live scholarships and grants for: "${query}"${profileDetails}. Provide concrete, detailed scholarship opportunities with clickable links.`;

    try {
      const response = await fetch('/api/search', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
              history: [],
              message: promptMessage,
              systemInstruction,
              apiKey: customKey || undefined
          })
      });
      
      const contentType = response.headers.get('content-type');
      const isJson = contentType && contentType.includes('application/json');

      if (isJson) {
        const textResponse = await response.text();
        const data = JSON.parse(textResponse);
        if (response.ok && data?.text && !data.text.includes("Dưới đây là các thông tin trọng tâm tổng hợp từ dữ liệu tuyển sinh")) {
          return {
            text: cleanMarkdownAsterisks(data.text),
            groundingMetadata: data.groundingMetadata || null
          };
        }
      }
    } catch (e) {
      console.warn("Backend scholarship search fetch error:", e);
    }

    // Direct Client Generation via GoogleGenAI SDK with Search Grounding
    if (customKey) {
      try {
        const ai = new GoogleGenAI({ apiKey: customKey });
        const aiResponse = await generateClientContentWithFallback(ai, {
            model: 'gemini-3.6-flash',
            contents: [{ role: 'user', parts: [{ text: promptMessage }] }],
            config: { 
              systemInstruction,
              tools: [{ googleSearch: {} }]
            }
        });
        if (aiResponse.text) {
          return {
            text: cleanMarkdownAsterisks(aiResponse.text),
            groundingMetadata: aiResponse.candidates?.[0]?.groundingMetadata || null
          };
        }
      } catch (clientErr) {
        console.warn("Client-side scholarship search error:", clientErr);
      }
    }

    // Dynamic AI structured synthesis if remote search tool is offline
    const fallbackPrompt = `Lập danh sách 3 chương trình học bổng uy tín nhất phù hợp với ngành/chủ đề "${query}" kèm điều kiện xét tuyển, giá trị học bổng và hạn nộp có link tham khảo.`;
    const text = await requestAiContent(fallbackPrompt, systemInstruction, language);
    return {
      text: cleanMarkdownAsterisks(text),
      groundingMetadata: null
    };
  };

  try {
    return await retryWithBackoff(callApi);
  } catch (error: any) {
    console.error("Scholarship search error:", error);
    throw new Error(cleanFrontEndErrorMessage(error, language));
  }
};

export const evaluateScholarshipProfile = async (
  profileData: {
    gpa: string;
    languageCert: string;
    major: string;
    targetCountry: string;
    activities: string;
    targetScholarship?: string;
  },
  language: Language,
  userProfile?: UserProfile | null
): Promise<string> => {
  const isVi = language === Language.VI;
  const systemInstruction = isVi
    ? `Bạn là Trưởng ban tuyển sinh và Cố vấn Săn học bổng Quốc tế cao cấp. Hãy đánh giá chi tiết và khách quan hồ sơ ứng viên sau đây đối với việc xin học bổng ${profileData.targetScholarship ? `"${profileData.targetScholarship}"` : 'các trường Đại học / Quỹ quốc tế'}.
Cung cấp phân tích sâu sắc theo định dạng:
### 📊 1. Điểm Đánh Giá Năng Lực Hồ Sơ
- **Điểm tổng quan hồ sơ (Profile Strength)**: [Ví dụ: 82/100 - Khá Mạnh / Xuất Sắc]
- **Tỷ lệ trúng tuyển ước tính**: [% trúng học bổng Toàn phần / Bán phần]

### 💎 2. Phân Tích Điểm Mạnh & Lợi Thế Cạnh Tranh
- Các điểm nổi bật về học thuật, ngoại ngữ và hoạt động.

### ⚠️ 3. Lỗ Hổng & Điểm Cần Cải Thiện Cấp Tốc
- Những tiêu chí còn thiếu hoặc cần nâng cấp trước kỳ hạn nộp đơn.

### 🎯 4. Danh Sách Học Bổng Tương Thích Nhất (Matching Scholarships)
- 3 chương trình học bổng thực tế phù hợp nhất với ngưỡng điểm này.

### 🚀 5. Lộ Trình Hành Động 4 Bước Tối Ưu Tỷ Lệ Đậu
- Kế hoạch từng tháng để nâng cấp bài luận, xin thư giới thiệu và nộp đơn.`
    : `You are a Senior Scholarship Board Evaluator. Perform an in-depth audit of the applicant's profile for ${profileData.targetScholarship ? `"${profileData.targetScholarship}"` : 'international scholarships'}.
Format response:
### 📊 1. Profile Competitiveness Score
- **Overall Profile Score**: [e.g. 85/100]
- **Estimated Acceptance Probability**: [Full-ride vs Partial %]

### 💎 2. Competitive Strengths
### ⚠️ 3. Critical Gaps & Weaknesses to Address
### 🎯 4. Top Matched Scholarship Programs
### 🚀 5. Strategic 4-Step Action Plan to Maximize Success`;

  const prompt = isVi
    ? `Thông tin ứng viên:
- Điểm GPA: ${profileData.gpa || 'Chưa cung cấp'}
- Chứng chỉ ngoại ngữ: ${profileData.languageCert || 'Chưa cung cấp'}
- Ngành học mục tiêu: ${profileData.major || 'Đa ngành'}
- Quốc gia/Khu vực mong muốn: ${profileData.targetCountry || 'Toàn cầu'}
- Hoạt động ngoại khóa / Nghiên cứu / Giải thưởng: ${profileData.activities || 'Chưa có nhiều'}
${profileData.targetScholarship ? `- Học bổng nhắm tới: ${profileData.targetScholarship}` : ''}`
    : `Applicant profile:
- GPA: ${profileData.gpa || 'Not provided'}
- English / Language Proficiency: ${profileData.languageCert || 'Not provided'}
- Target Major: ${profileData.major || 'General'}
- Target Region: ${profileData.targetCountry || 'Global'}
- Extracurriculars / Projects / Awards: ${profileData.activities || 'None specified'}
${profileData.targetScholarship ? `- Target Scholarship: ${profileData.targetScholarship}` : ''}`;

  const text = await requestAiContent(prompt, systemInstruction, language);
  return cleanMarkdownAsterisks(text);
};

export const generateScholarshipEssayOutline = async (
  essayData: {
    scholarshipName: string;
    intendedMajor: string;
    whyMajor: string;
    uniqueExperience: string;
    futureContribution: string;
  },
  language: Language
): Promise<string> => {
  const isVi = language === Language.VI;
  const systemInstruction = isVi
    ? `Bạn là Chuyên gia luyện viết Luận Học bổng & Thư Động Lực (Statement of Purpose / Motivation Letter) quốc tế. Hãy xây dựng một cấu trúc bài luận thuyết phục, cảm xúc và đậm chất cá nhân hóa cho học bổng "${essayData.scholarshipName || 'Đại học Toàn Cầu'}".
Cung cấp:
### ✍️ 1. Tiêu Đề Bài Luận & Thông Điệp Cốt Lõi (Core Hook & Theme)
### 🌟 2. Đoạn Mở Đầu Ấn Tượng (Opening Hook - Viết mẫu 1 đoạn cuốn hút)
### 🧱 3. Dàn Ý Chi Tiết Thân Bài (Body Paragraphs Outline):
- **Phần 1: Khởi nguồn đam mê & Động lực học tập**
- **Phần 2: Trải nghiệm thực tế & Năng lực vượt trội**
- **Phần 3: Lý do chọn trường / quốc gia / quỹ học bổng này**
- **Phần 4: Kế hoạch tương lai & Giá trị đóng góp cho cộng đồng**
### 🎯 4. Đoạn Kết Bài Gây Dấu Ấn (Memorable Conclusion)
### 💡 5. Ba Lỗi Thường Gặp Cần Tránh Khi Nộp Bài Luận Này`
    : `You are an elite Scholarship Essay & Motivation Letter Coach. Generate an outline and compelling writing strategy for "${essayData.scholarshipName || 'Global Scholarship'}".
Include:
### ✍️ 1. Essay Title & Core Narrative Theme
### 🌟 2. Sample Compelling Opening Hook
### 🧱 3. Detailed Body Paragraphs Outline
### 🎯 4. Memorable Conclusion
### 💡 5. Top 3 Pitfalls to Avoid`;

  const prompt = isVi
    ? `Thông tin viết bài luận:
- Học bổng: ${essayData.scholarshipName || 'Học bổng đại học'}
- Ngành học: ${essayData.intendedMajor || 'Chưa chỉ định'}
- Lý do đam mê ngành này: ${essayData.whyMajor || 'Đam mê phát triển bản thân và giải quyết vấn đề xã hội'}
- Trải nghiệm nổi bật / Khó khăn đã vượt qua: ${essayData.uniqueExperience || 'Chưa cung cấp'}
- Đóng góp trong tương lai: ${essayData.futureContribution || 'Đóng góp tri thức và đổi mới sáng tạo'}`
    : `Essay parameters:
- Scholarship: ${essayData.scholarshipName || 'University Scholarship'}
- Major: ${essayData.intendedMajor || 'Undecided'}
- Motivation for major: ${essayData.whyMajor || 'Passion for solving societal challenges'}
- Key personal story / obstacle overcome: ${essayData.uniqueExperience || 'Not specified'}
- Future contribution: ${essayData.futureContribution || 'Contributing to innovation'}`;

  const text = await requestAiContent(prompt, systemInstruction, language);
  return cleanMarkdownAsterisks(text);
};

export const generateMockInterviewQuestions = async (
  job: string,
  level: string,
  tone: string,
  targetCompany?: string,
  language: Language = Language.VI
): Promise<string[]> => {
  const isEn = language === Language.EN;
  const systemPrompt = "You are an expert HR Manager and artificial career interviewer. You must generate EXACTLY 4 highly relevant and customized interview questions for a candidate.";
  const userMessage = `Create 4 tailored interview questions for the position of "${job}" with "${level}" experience level.
The interviewer tone should be "${tone}".
${targetCompany ? `Target Hiring Company: "${targetCompany}". Adapt questions to the specific culture and hiring process of ${targetCompany}.` : ''}
Return the output strictly as a JSON array of 4 string questions. Do not write anything else. Do not use markdown \`\`\`json.`;

  const customKey = getGeminiApiKey();
  
  try {
    const response = await fetch('/api/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        history: [],
        message: userMessage,
        systemInstruction: systemPrompt,
        apiKey: customKey || undefined
      })
    });
    if (response.ok) {
      const data = await response.json();
      if (data?.text) {
        let clean = data.text.trim();
        const firstBracket = clean.indexOf('[');
        const lastBracket = clean.lastIndexOf(']');
        if (firstBracket !== -1 && lastBracket > firstBracket) {
          clean = clean.substring(firstBracket, lastBracket + 1);
        }
        const parsed = JSON.parse(clean);
        if (Array.isArray(parsed) && parsed.length > 0) {
          return parsed.map((q: string) => cleanMarkdownAsterisks(q));
        }
      }
    }
  } catch (err) {
    console.warn("Backend chat query failed for questions, attempting direct client AI...", err);
  }

  if (customKey) {
    try {
      const ai = new GoogleGenAI({ apiKey: customKey });
      const aiResponse = await generateClientContentWithFallback(ai, {
        model: 'gemini-3.6-flash',
        contents: [{ role: 'user', parts: [{ text: userMessage }] }],
        config: { systemInstruction: systemPrompt }
      });
      let clean = (aiResponse.text || '').trim();
      const firstBracket = clean.indexOf('[');
      const lastBracket = clean.lastIndexOf(']');
      if (firstBracket !== -1 && lastBracket > firstBracket) {
        clean = clean.substring(firstBracket, lastBracket + 1);
      }
      const parsed = JSON.parse(clean);
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed.map((q: string) => cleanMarkdownAsterisks(q));
      }
    } catch (clientErr) {
      console.warn("Client SDK failed for questions:", clientErr);
    }
  }

  throw new Error(isEn ? "Failed to generate interview questions. Please verify your AI settings and API key." : "Không thể tạo câu hỏi phỏng vấn bằng AI. Vui lòng kiểm tra thiết lập API Key.");
};

export const evaluateMockInterviewTranscript = async (
  job: string,
  level: string,
  tone: string,
  questions: string[],
  answers: string[],
  language: Language = Language.VI
): Promise<any> => {
  const isVi = language === Language.VI;
  const systemInstruction = "You are an elite HR consultant analyzing interview transcripts. You must analyze the questions and candidates answers then evaluate performance objectively. Return EXACTLY a JSON object matching the specified schema.";

  const transcript = questions.map((q, i) => `Question ${i + 1}: ${q}\nAnswer: ${answers[i] || 'No answer'}`).join('\n\n');

  const userMessage = `Role: ${job} (Level: ${level})
Interviewer Tone: ${tone}

Evaluate this interview transcript:
${transcript}

Return a valid JSON object matching this structure EXACTLY:
{
  "score": <number from 0 to 100>,
  "overallFeedback": "<string details summarizing performance with constructive advice in ${isVi ? 'Vietnamese' : 'English'}>",
  "strengths": ["<strength 1>", "<strength 2>", "<strength 3>"],
  "weaknesses": ["<weakness 1>", "<weakness 2>"],
  "recommendations": ["<recommendation 1>", "<recommendation 2>"],
  "categories": {
    "knowledge": <number from 0 to 100>,
    "communication": <number from 0 to 100>,
    "problemSolving": <number from 0 to 100>,
    "riasecFit": <number from 0 to 100>
  }
}

Rule: Do NOT output anything other than this JSON structure. Do NOT write markdown code fences. Respond in ${isVi ? "Vietnamese" : "English"}.`;

  const customKey = getGeminiApiKey();

  try {
    const response = await fetch('/api/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        history: [],
        message: userMessage,
        systemInstruction,
        apiKey: customKey || undefined
      })
    });
    if (response.ok) {
      const data = await response.json();
      if (data?.text) {
        let clean = data.text.trim();
        const firstBrace = clean.indexOf('{');
        const lastBrace = clean.lastIndexOf('}');
        if (firstBrace !== -1 && lastBrace > firstBrace) {
          clean = clean.substring(firstBrace, lastBrace + 1);
        }
        const parsed = JSON.parse(clean);
        if (parsed && typeof parsed.score === 'number') {
          return cleanMarkdownAsterisks(parsed);
        }
      }
    }
  } catch (err) {
    console.warn("Backend evaluation request failed, trying client SDK...", err);
  }

  if (customKey) {
    try {
      const ai = new GoogleGenAI({ apiKey: customKey });
      const aiResponse = await generateClientContentWithFallback(ai, {
        model: 'gemini-3.6-flash',
        contents: [{ role: 'user', parts: [{ text: userMessage }] }],
        config: { systemInstruction }
      });
      let clean = (aiResponse.text || '').trim();
      const firstBrace = clean.indexOf('{');
      const lastBrace = clean.lastIndexOf('}');
      if (firstBrace !== -1 && lastBrace > firstBrace) {
        clean = clean.substring(firstBrace, lastBrace + 1);
      }
      const parsed = JSON.parse(clean);
      if (parsed && typeof parsed.score === 'number') {
        return cleanMarkdownAsterisks(parsed);
      }
    } catch (clientErr) {
      console.warn("Client SDK failed for evaluation:", clientErr);
    }
  }

  throw new Error(isVi ? "Đánh giá bằng AI thất bại. Vui lòng kiểm tra API Key." : "AI Evaluation failed. Please check your API key.");
};
